// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="calculate_calculate,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-2,HLS_INPUT_CLOCK=2.500000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=4.725000,HLS_SYN_LAT=18,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3717,HLS_SYN_LUT=2054,HLS_VERSION=2024_1}" *)

module calculate (
        ap_clk,
        ap_rst,
        data_new,
        data_old,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [383:0] data_new;
input  [383:0] data_old;
output  [54:0] ap_return;

wire   [24:0] add01_fu_300_p2;
reg   [24:0] add01_reg_1146;
wire    ap_block_pp0_stage0_11001;
wire   [24:0] add23_fu_314_p2;
reg   [24:0] add23_reg_1151;
wire   [24:0] add45_fu_328_p2;
reg   [24:0] add45_reg_1156;
wire   [24:0] add67_fu_342_p2;
reg   [24:0] add67_reg_1161;
wire   [24:0] add89_fu_356_p2;
reg   [24:0] add89_reg_1166;
wire   [24:0] addAB_fu_370_p2;
reg   [24:0] addAB_reg_1171;
wire   [24:0] addCD_fu_384_p2;
reg   [24:0] addCD_reg_1176;
wire   [24:0] addEF_fu_398_p2;
reg   [24:0] addEF_reg_1181;
wire   [24:0] add01_1_fu_566_p2;
reg   [24:0] add01_1_reg_1186;
wire   [24:0] add23_1_fu_580_p2;
reg   [24:0] add23_1_reg_1191;
wire   [24:0] add45_1_fu_594_p2;
reg   [24:0] add45_1_reg_1196;
wire   [24:0] add67_1_fu_608_p2;
reg   [24:0] add67_1_reg_1201;
wire   [24:0] add89_1_fu_622_p2;
reg   [24:0] add89_1_reg_1206;
wire   [24:0] addAB_1_fu_636_p2;
reg   [24:0] addAB_1_reg_1211;
wire   [24:0] addCD_1_fu_650_p2;
reg   [24:0] addCD_1_reg_1216;
wire   [24:0] addEF_1_fu_664_p2;
reg   [24:0] addEF_1_reg_1221;
wire   [25:0] add03_fu_676_p2;
reg   [25:0] add03_reg_1226;
wire   [25:0] add47_fu_688_p2;
reg   [25:0] add47_reg_1231;
wire   [25:0] add8B_fu_700_p2;
reg   [25:0] add8B_reg_1236;
wire   [25:0] addCF_fu_712_p2;
reg   [25:0] addCF_reg_1241;
wire   [25:0] add03_1_fu_724_p2;
reg   [25:0] add03_1_reg_1246;
wire   [25:0] add47_1_fu_736_p2;
reg   [25:0] add47_1_reg_1251;
wire   [25:0] add8B_1_fu_748_p2;
reg   [25:0] add8B_1_reg_1256;
wire   [25:0] addCF_1_fu_760_p2;
reg   [25:0] addCF_1_reg_1261;
wire  signed [26:0] add07_fu_772_p2;
reg  signed [26:0] add07_reg_1266;
wire  signed [26:0] add8F_fu_784_p2;
reg  signed [26:0] add8F_reg_1272;
wire  signed [26:0] add07_1_fu_796_p2;
reg  signed [26:0] add07_1_reg_1278;
wire  signed [26:0] add8F_1_fu_808_p2;
reg  signed [26:0] add8F_1_reg_1284;
wire   [26:0] add0F_fu_826_p2;
reg   [26:0] add0F_reg_1290;
reg   [26:0] add0F_reg_1290_pp0_iter4_reg;
wire   [26:0] add0F_1_fu_842_p2;
reg   [26:0] add0F_1_reg_1296;
reg   [26:0] add0F_1_reg_1296_pp0_iter4_reg;
reg   [0:0] tmp_reg_1302;
reg   [0:0] tmp_reg_1302_pp0_iter4_reg;
reg   [0:0] tmp_1_reg_1307;
reg   [0:0] tmp_1_reg_1307_pp0_iter4_reg;
wire   [26:0] sub_ln61_fu_862_p2;
reg   [26:0] sub_ln61_reg_1312;
wire   [26:0] sub_ln61_1_fu_867_p2;
reg   [26:0] sub_ln61_1_reg_1317;
reg   [8:0] high_reg_1322;
reg   [8:0] medium_reg_1327;
wire   [8:0] low_fu_902_p1;
reg   [8:0] low_reg_1332;
reg   [8:0] high_1_reg_1337;
reg   [8:0] medium_1_reg_1342;
wire   [8:0] low_1_fu_926_p1;
reg   [8:0] low_1_reg_1347;
wire   [17:0] zext_ln75_fu_930_p1;
reg   [17:0] zext_ln75_reg_1352;
reg   [17:0] zext_ln75_reg_1352_pp0_iter7_reg;
reg   [17:0] zext_ln75_reg_1352_pp0_iter8_reg;
wire   [17:0] zext_ln76_fu_939_p1;
reg   [17:0] zext_ln76_reg_1360;
reg   [17:0] zext_ln76_reg_1360_pp0_iter7_reg;
reg   [17:0] zext_ln76_reg_1360_pp0_iter8_reg;
wire   [17:0] zext_ln77_fu_942_p1;
reg   [17:0] zext_ln77_reg_1368;
reg   [17:0] zext_ln77_reg_1368_pp0_iter7_reg;
reg   [17:0] zext_ln77_reg_1368_pp0_iter8_reg;
wire   [17:0] zext_ln75_1_fu_957_p1;
reg   [17:0] zext_ln75_1_reg_1376;
reg   [17:0] zext_ln75_1_reg_1376_pp0_iter7_reg;
reg   [17:0] zext_ln75_1_reg_1376_pp0_iter8_reg;
wire   [17:0] zext_ln76_1_fu_966_p1;
reg   [17:0] zext_ln76_1_reg_1384;
reg   [17:0] zext_ln76_1_reg_1384_pp0_iter7_reg;
reg   [17:0] zext_ln76_1_reg_1384_pp0_iter8_reg;
wire   [17:0] zext_ln77_1_fu_969_p1;
reg   [17:0] zext_ln77_1_reg_1392;
reg   [17:0] zext_ln77_1_reg_1392_pp0_iter7_reg;
reg   [17:0] zext_ln77_1_reg_1392_pp0_iter8_reg;
wire   [17:0] grp_fu_933_p2;
reg   [17:0] h2_reg_1400;
wire   [17:0] grp_fu_945_p2;
reg   [17:0] hl_reg_1405;
wire   [17:0] grp_fu_951_p2;
reg   [17:0] ml_reg_1410;
wire   [17:0] grp_fu_960_p2;
reg   [17:0] h2_1_reg_1415;
wire   [17:0] grp_fu_972_p2;
reg   [17:0] hl_1_reg_1420;
wire   [17:0] grp_fu_978_p2;
reg   [17:0] ml_1_reg_1425;
wire   [25:0] grp_fu_1122_p3;
reg   [25:0] h2_hm_reg_1460;
reg   [25:0] h2_hm_reg_1460_pp0_iter13_reg;
reg   [25:0] h2_hm_reg_1460_pp0_iter14_reg;
wire   [19:0] grp_fu_1110_p3;
reg   [19:0] m2_hl_reg_1465;
wire   [27:0] grp_fu_1116_p3;
reg   [27:0] l2_ml_reg_1470;
wire   [25:0] grp_fu_1140_p3;
reg   [25:0] h2_hm_1_reg_1475;
reg   [25:0] h2_hm_1_reg_1475_pp0_iter13_reg;
reg   [25:0] h2_hm_1_reg_1475_pp0_iter14_reg;
wire   [19:0] grp_fu_1128_p3;
reg   [19:0] m2_hl_1_reg_1480;
wire   [27:0] grp_fu_1134_p3;
reg   [27:0] l2_ml_1_reg_1485;
wire   [37:0] grp_fu_1044_p2;
reg   [37:0] m2_hl_l2_ml_reg_1510;
wire   [37:0] grp_fu_1060_p2;
reg   [37:0] m2_hl_l2_ml_1_reg_1515;
wire   [53:0] grp_fu_1076_p2;
reg   [53:0] h2_hm_m2_hl_l2_ml_reg_1540;
wire   [53:0] grp_fu_1092_p2;
reg   [53:0] h2_hm_m2_hl_l2_ml_1_reg_1545;
wire    ap_block_pp0_stage0;
wire   [23:0] mic_fu_138_p1;
wire   [23:0] mic_1_fu_142_p4;
wire  signed [24:0] sext_ln36_1_fu_296_p1;
wire  signed [24:0] sext_ln36_fu_292_p1;
wire   [23:0] mic_2_fu_152_p4;
wire   [23:0] mic_3_fu_162_p4;
wire  signed [24:0] sext_ln37_1_fu_310_p1;
wire  signed [24:0] sext_ln37_fu_306_p1;
wire   [23:0] mic_4_fu_172_p4;
wire   [23:0] mic_5_fu_182_p4;
wire  signed [24:0] sext_ln38_1_fu_324_p1;
wire  signed [24:0] sext_ln38_fu_320_p1;
wire   [23:0] mic_6_fu_192_p4;
wire   [23:0] mic_7_fu_202_p4;
wire  signed [24:0] sext_ln39_1_fu_338_p1;
wire  signed [24:0] sext_ln39_fu_334_p1;
wire   [23:0] mic_8_fu_212_p4;
wire   [23:0] mic_9_fu_222_p4;
wire  signed [24:0] sext_ln40_1_fu_352_p1;
wire  signed [24:0] sext_ln40_fu_348_p1;
wire   [23:0] mic_10_fu_232_p4;
wire   [23:0] mic_11_fu_242_p4;
wire  signed [24:0] sext_ln41_1_fu_366_p1;
wire  signed [24:0] sext_ln41_fu_362_p1;
wire   [23:0] mic_12_fu_252_p4;
wire   [23:0] mic_13_fu_262_p4;
wire  signed [24:0] sext_ln42_1_fu_380_p1;
wire  signed [24:0] sext_ln42_fu_376_p1;
wire   [23:0] mic_14_fu_272_p4;
wire   [23:0] mic_15_fu_282_p4;
wire  signed [24:0] sext_ln43_1_fu_394_p1;
wire  signed [24:0] sext_ln43_fu_390_p1;
wire   [23:0] mic_16_fu_404_p1;
wire   [23:0] mic_17_fu_408_p4;
wire  signed [24:0] sext_ln36_3_fu_562_p1;
wire  signed [24:0] sext_ln36_2_fu_558_p1;
wire   [23:0] mic_18_fu_418_p4;
wire   [23:0] mic_19_fu_428_p4;
wire  signed [24:0] sext_ln37_3_fu_576_p1;
wire  signed [24:0] sext_ln37_2_fu_572_p1;
wire   [23:0] mic_20_fu_438_p4;
wire   [23:0] mic_21_fu_448_p4;
wire  signed [24:0] sext_ln38_3_fu_590_p1;
wire  signed [24:0] sext_ln38_2_fu_586_p1;
wire   [23:0] mic_22_fu_458_p4;
wire   [23:0] mic_23_fu_468_p4;
wire  signed [24:0] sext_ln39_3_fu_604_p1;
wire  signed [24:0] sext_ln39_2_fu_600_p1;
wire   [23:0] mic_24_fu_478_p4;
wire   [23:0] mic_25_fu_488_p4;
wire  signed [24:0] sext_ln40_3_fu_618_p1;
wire  signed [24:0] sext_ln40_2_fu_614_p1;
wire   [23:0] mic_26_fu_498_p4;
wire   [23:0] mic_27_fu_508_p4;
wire  signed [24:0] sext_ln41_3_fu_632_p1;
wire  signed [24:0] sext_ln41_2_fu_628_p1;
wire   [23:0] mic_28_fu_518_p4;
wire   [23:0] mic_29_fu_528_p4;
wire  signed [24:0] sext_ln42_3_fu_646_p1;
wire  signed [24:0] sext_ln42_2_fu_642_p1;
wire   [23:0] mic_30_fu_538_p4;
wire   [23:0] mic_31_fu_548_p4;
wire  signed [24:0] sext_ln43_3_fu_660_p1;
wire  signed [24:0] sext_ln43_2_fu_656_p1;
wire  signed [25:0] sext_ln45_1_fu_673_p1;
wire  signed [25:0] sext_ln45_fu_670_p1;
wire  signed [25:0] sext_ln46_1_fu_685_p1;
wire  signed [25:0] sext_ln46_fu_682_p1;
wire  signed [25:0] sext_ln47_1_fu_697_p1;
wire  signed [25:0] sext_ln47_fu_694_p1;
wire  signed [25:0] sext_ln48_1_fu_709_p1;
wire  signed [25:0] sext_ln48_fu_706_p1;
wire  signed [25:0] sext_ln45_3_fu_721_p1;
wire  signed [25:0] sext_ln45_2_fu_718_p1;
wire  signed [25:0] sext_ln46_3_fu_733_p1;
wire  signed [25:0] sext_ln46_2_fu_730_p1;
wire  signed [25:0] sext_ln47_3_fu_745_p1;
wire  signed [25:0] sext_ln47_2_fu_742_p1;
wire  signed [25:0] sext_ln48_3_fu_757_p1;
wire  signed [25:0] sext_ln48_2_fu_754_p1;
wire  signed [26:0] sext_ln50_1_fu_769_p1;
wire  signed [26:0] sext_ln50_fu_766_p1;
wire  signed [26:0] sext_ln51_1_fu_781_p1;
wire  signed [26:0] sext_ln51_fu_778_p1;
wire  signed [26:0] sext_ln50_3_fu_793_p1;
wire  signed [26:0] sext_ln50_2_fu_790_p1;
wire  signed [26:0] sext_ln51_3_fu_805_p1;
wire  signed [26:0] sext_ln51_2_fu_802_p1;
wire  signed [27:0] sext_ln53_1_fu_817_p1;
wire  signed [27:0] sext_ln53_fu_814_p1;
wire  signed [27:0] sext_ln53_3_fu_833_p1;
wire  signed [27:0] sext_ln53_2_fu_830_p1;
wire   [27:0] add_ln53_fu_820_p2;
wire   [27:0] add_ln53_3_fu_836_p2;
wire   [26:0] abs_new_0_in_fu_872_p3;
wire   [26:0] abs_old_0_in_fu_877_p3;
wire   [8:0] grp_fu_933_p0;
wire   [8:0] grp_fu_933_p1;
wire   [8:0] grp_fu_945_p0;
wire   [8:0] grp_fu_945_p1;
wire   [8:0] grp_fu_951_p0;
wire   [8:0] grp_fu_951_p1;
wire   [8:0] grp_fu_960_p0;
wire   [8:0] grp_fu_960_p1;
wire   [8:0] grp_fu_972_p0;
wire   [8:0] grp_fu_972_p1;
wire   [8:0] grp_fu_978_p0;
wire   [8:0] grp_fu_978_p1;
wire   [18:0] shl_ln1_fu_991_p3;
wire   [18:0] shl_ln83_1_fu_1016_p3;
wire   [37:0] grp_fu_1044_p0;
wire   [37:0] grp_fu_1044_p1;
wire   [37:0] grp_fu_1060_p0;
wire   [37:0] grp_fu_1060_p1;
wire   [53:0] grp_fu_1076_p0;
wire   [53:0] grp_fu_1076_p1;
wire   [53:0] grp_fu_1092_p0;
wire   [53:0] grp_fu_1092_p1;
wire   [54:0] grp_fu_1104_p0;
wire   [54:0] grp_fu_1104_p1;
wire   [8:0] grp_fu_1110_p0;
wire   [8:0] grp_fu_1110_p1;
wire   [18:0] grp_fu_1110_p2;
wire   [8:0] grp_fu_1116_p0;
wire   [8:0] grp_fu_1116_p1;
wire   [27:0] grp_fu_1116_p2;
wire   [8:0] grp_fu_1122_p0;
wire   [8:0] grp_fu_1122_p1;
wire   [25:0] grp_fu_1122_p2;
wire   [8:0] grp_fu_1128_p0;
wire   [8:0] grp_fu_1128_p1;
wire   [18:0] grp_fu_1128_p2;
wire   [8:0] grp_fu_1134_p0;
wire   [8:0] grp_fu_1134_p1;
wire   [27:0] grp_fu_1134_p2;
wire   [8:0] grp_fu_1140_p0;
wire   [8:0] grp_fu_1140_p1;
wire   [25:0] grp_fu_1140_p2;
wire   [54:0] grp_fu_1104_p2;
wire   [19:0] grp_fu_1110_p20;
wire   [19:0] grp_fu_1128_p20;
wire   [17:0] grp_fu_951_p10;
wire   [17:0] grp_fu_978_p10;
wire    ap_ce_reg;

calculate_mul_9ns_9ns_18_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9ns_9ns_18_5_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_933_p0),
    .din1(grp_fu_933_p1),
    .ce(1'b1),
    .dout(grp_fu_933_p2)
);

calculate_mul_9ns_9ns_18_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9ns_9ns_18_5_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_945_p0),
    .din1(grp_fu_945_p1),
    .ce(1'b1),
    .dout(grp_fu_945_p2)
);

calculate_mul_9ns_9ns_18_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9ns_9ns_18_5_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_951_p0),
    .din1(grp_fu_951_p1),
    .ce(1'b1),
    .dout(grp_fu_951_p2)
);

calculate_mul_9ns_9ns_18_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9ns_9ns_18_5_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_960_p0),
    .din1(grp_fu_960_p1),
    .ce(1'b1),
    .dout(grp_fu_960_p2)
);

calculate_mul_9ns_9ns_18_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9ns_9ns_18_5_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_972_p0),
    .din1(grp_fu_972_p1),
    .ce(1'b1),
    .dout(grp_fu_972_p2)
);

calculate_mul_9ns_9ns_18_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9ns_9ns_18_5_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_978_p0),
    .din1(grp_fu_978_p1),
    .ce(1'b1),
    .dout(grp_fu_978_p2)
);

calculate_add_38ns_38ns_38_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 38 ),
    .din1_WIDTH( 38 ),
    .dout_WIDTH( 38 ))
add_38ns_38ns_38_2_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1044_p0),
    .din1(grp_fu_1044_p1),
    .ce(1'b1),
    .dout(grp_fu_1044_p2)
);

calculate_add_38ns_38ns_38_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 38 ),
    .din1_WIDTH( 38 ),
    .dout_WIDTH( 38 ))
add_38ns_38ns_38_2_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1060_p0),
    .din1(grp_fu_1060_p1),
    .ce(1'b1),
    .dout(grp_fu_1060_p2)
);

calculate_add_54ns_54ns_54_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 54 ),
    .din1_WIDTH( 54 ),
    .dout_WIDTH( 54 ))
add_54ns_54ns_54_2_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1076_p0),
    .din1(grp_fu_1076_p1),
    .ce(1'b1),
    .dout(grp_fu_1076_p2)
);

calculate_add_54ns_54ns_54_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 54 ),
    .din1_WIDTH( 54 ),
    .dout_WIDTH( 54 ))
add_54ns_54ns_54_2_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1092_p0),
    .din1(grp_fu_1092_p1),
    .ce(1'b1),
    .dout(grp_fu_1092_p2)
);

calculate_sub_55ns_55ns_55_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 55 ),
    .din1_WIDTH( 55 ),
    .dout_WIDTH( 55 ))
sub_55ns_55ns_55_2_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1104_p0),
    .din1(grp_fu_1104_p1),
    .ce(1'b1),
    .dout(grp_fu_1104_p2)
);

calculate_mac_muladd_9ns_9ns_19ns_20_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
mac_muladd_9ns_9ns_19ns_20_4_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1110_p0),
    .din1(grp_fu_1110_p1),
    .din2(grp_fu_1110_p2),
    .ce(1'b1),
    .dout(grp_fu_1110_p3)
);

calculate_mac_muladd_9ns_9ns_28ns_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
mac_muladd_9ns_9ns_28ns_28_4_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1116_p0),
    .din1(grp_fu_1116_p1),
    .din2(grp_fu_1116_p2),
    .ce(1'b1),
    .dout(grp_fu_1116_p3)
);

calculate_mac_muladd_9ns_9ns_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_9ns_9ns_26ns_26_4_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1122_p0),
    .din1(grp_fu_1122_p1),
    .din2(grp_fu_1122_p2),
    .ce(1'b1),
    .dout(grp_fu_1122_p3)
);

calculate_mac_muladd_9ns_9ns_19ns_20_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
mac_muladd_9ns_9ns_19ns_20_4_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1128_p0),
    .din1(grp_fu_1128_p1),
    .din2(grp_fu_1128_p2),
    .ce(1'b1),
    .dout(grp_fu_1128_p3)
);

calculate_mac_muladd_9ns_9ns_28ns_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
mac_muladd_9ns_9ns_28ns_28_4_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1134_p0),
    .din1(grp_fu_1134_p1),
    .din2(grp_fu_1134_p2),
    .ce(1'b1),
    .dout(grp_fu_1134_p3)
);

calculate_mac_muladd_9ns_9ns_26ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_9ns_9ns_26ns_26_4_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1140_p0),
    .din1(grp_fu_1140_p1),
    .din2(grp_fu_1140_p2),
    .ce(1'b1),
    .dout(grp_fu_1140_p3)
);

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add01_1_reg_1186 <= add01_1_fu_566_p2;
        add01_reg_1146 <= add01_fu_300_p2;
        add03_1_reg_1246 <= add03_1_fu_724_p2;
        add03_reg_1226 <= add03_fu_676_p2;
        add07_1_reg_1278 <= add07_1_fu_796_p2;
        add07_reg_1266 <= add07_fu_772_p2;
        add0F_1_reg_1296 <= add0F_1_fu_842_p2;
        add0F_1_reg_1296_pp0_iter4_reg <= add0F_1_reg_1296;
        add0F_reg_1290 <= add0F_fu_826_p2;
        add0F_reg_1290_pp0_iter4_reg <= add0F_reg_1290;
        add23_1_reg_1191 <= add23_1_fu_580_p2;
        add23_reg_1151 <= add23_fu_314_p2;
        add45_1_reg_1196 <= add45_1_fu_594_p2;
        add45_reg_1156 <= add45_fu_328_p2;
        add47_1_reg_1251 <= add47_1_fu_736_p2;
        add47_reg_1231 <= add47_fu_688_p2;
        add67_1_reg_1201 <= add67_1_fu_608_p2;
        add67_reg_1161 <= add67_fu_342_p2;
        add89_1_reg_1206 <= add89_1_fu_622_p2;
        add89_reg_1166 <= add89_fu_356_p2;
        add8B_1_reg_1256 <= add8B_1_fu_748_p2;
        add8B_reg_1236 <= add8B_fu_700_p2;
        add8F_1_reg_1284 <= add8F_1_fu_808_p2;
        add8F_reg_1272 <= add8F_fu_784_p2;
        addAB_1_reg_1211 <= addAB_1_fu_636_p2;
        addAB_reg_1171 <= addAB_fu_370_p2;
        addCD_1_reg_1216 <= addCD_1_fu_650_p2;
        addCD_reg_1176 <= addCD_fu_384_p2;
        addCF_1_reg_1261 <= addCF_1_fu_760_p2;
        addCF_reg_1241 <= addCF_fu_712_p2;
        addEF_1_reg_1221 <= addEF_1_fu_664_p2;
        addEF_reg_1181 <= addEF_fu_398_p2;
        h2_1_reg_1415 <= grp_fu_960_p2;
        h2_hm_1_reg_1475 <= grp_fu_1140_p3;
        h2_hm_1_reg_1475_pp0_iter13_reg <= h2_hm_1_reg_1475;
        h2_hm_1_reg_1475_pp0_iter14_reg <= h2_hm_1_reg_1475_pp0_iter13_reg;
        h2_hm_m2_hl_l2_ml_1_reg_1545 <= grp_fu_1092_p2;
        h2_hm_m2_hl_l2_ml_reg_1540 <= grp_fu_1076_p2;
        h2_hm_reg_1460 <= grp_fu_1122_p3;
        h2_hm_reg_1460_pp0_iter13_reg <= h2_hm_reg_1460;
        h2_hm_reg_1460_pp0_iter14_reg <= h2_hm_reg_1460_pp0_iter13_reg;
        h2_reg_1400 <= grp_fu_933_p2;
        high_1_reg_1337 <= {{abs_old_0_in_fu_877_p3[26:18]}};
        high_reg_1322 <= {{abs_new_0_in_fu_872_p3[26:18]}};
        hl_1_reg_1420 <= grp_fu_972_p2;
        hl_reg_1405 <= grp_fu_945_p2;
        l2_ml_1_reg_1485 <= grp_fu_1134_p3;
        l2_ml_reg_1470 <= grp_fu_1116_p3;
        low_1_reg_1347 <= low_1_fu_926_p1;
        low_reg_1332 <= low_fu_902_p1;
        m2_hl_1_reg_1480 <= grp_fu_1128_p3;
        m2_hl_l2_ml_1_reg_1515 <= grp_fu_1060_p2;
        m2_hl_l2_ml_reg_1510 <= grp_fu_1044_p2;
        m2_hl_reg_1465 <= grp_fu_1110_p3;
        medium_1_reg_1342 <= {{abs_old_0_in_fu_877_p3[17:9]}};
        medium_reg_1327 <= {{abs_new_0_in_fu_872_p3[17:9]}};
        ml_1_reg_1425 <= grp_fu_978_p2;
        ml_reg_1410 <= grp_fu_951_p2;
        sub_ln61_1_reg_1317 <= sub_ln61_1_fu_867_p2;
        sub_ln61_reg_1312 <= sub_ln61_fu_862_p2;
        tmp_1_reg_1307 <= add_ln53_3_fu_836_p2[32'd27];
        tmp_1_reg_1307_pp0_iter4_reg <= tmp_1_reg_1307;
        tmp_reg_1302 <= add_ln53_fu_820_p2[32'd27];
        tmp_reg_1302_pp0_iter4_reg <= tmp_reg_1302;
        zext_ln75_1_reg_1376[8 : 0] <= zext_ln75_1_fu_957_p1[8 : 0];
        zext_ln75_1_reg_1376_pp0_iter7_reg[8 : 0] <= zext_ln75_1_reg_1376[8 : 0];
        zext_ln75_1_reg_1376_pp0_iter8_reg[8 : 0] <= zext_ln75_1_reg_1376_pp0_iter7_reg[8 : 0];
        zext_ln75_reg_1352[8 : 0] <= zext_ln75_fu_930_p1[8 : 0];
        zext_ln75_reg_1352_pp0_iter7_reg[8 : 0] <= zext_ln75_reg_1352[8 : 0];
        zext_ln75_reg_1352_pp0_iter8_reg[8 : 0] <= zext_ln75_reg_1352_pp0_iter7_reg[8 : 0];
        zext_ln76_1_reg_1384[8 : 0] <= zext_ln76_1_fu_966_p1[8 : 0];
        zext_ln76_1_reg_1384_pp0_iter7_reg[8 : 0] <= zext_ln76_1_reg_1384[8 : 0];
        zext_ln76_1_reg_1384_pp0_iter8_reg[8 : 0] <= zext_ln76_1_reg_1384_pp0_iter7_reg[8 : 0];
        zext_ln76_reg_1360[8 : 0] <= zext_ln76_fu_939_p1[8 : 0];
        zext_ln76_reg_1360_pp0_iter7_reg[8 : 0] <= zext_ln76_reg_1360[8 : 0];
        zext_ln76_reg_1360_pp0_iter8_reg[8 : 0] <= zext_ln76_reg_1360_pp0_iter7_reg[8 : 0];
        zext_ln77_1_reg_1392[8 : 0] <= zext_ln77_1_fu_969_p1[8 : 0];
        zext_ln77_1_reg_1392_pp0_iter7_reg[8 : 0] <= zext_ln77_1_reg_1392[8 : 0];
        zext_ln77_1_reg_1392_pp0_iter8_reg[8 : 0] <= zext_ln77_1_reg_1392_pp0_iter7_reg[8 : 0];
        zext_ln77_reg_1368[8 : 0] <= zext_ln77_fu_942_p1[8 : 0];
        zext_ln77_reg_1368_pp0_iter7_reg[8 : 0] <= zext_ln77_reg_1368[8 : 0];
        zext_ln77_reg_1368_pp0_iter8_reg[8 : 0] <= zext_ln77_reg_1368_pp0_iter7_reg[8 : 0];
    end
end

assign abs_new_0_in_fu_872_p3 = ((tmp_reg_1302_pp0_iter4_reg[0:0] == 1'b1) ? sub_ln61_reg_1312 : add0F_reg_1290_pp0_iter4_reg);

assign abs_old_0_in_fu_877_p3 = ((tmp_1_reg_1307_pp0_iter4_reg[0:0] == 1'b1) ? sub_ln61_1_reg_1317 : add0F_1_reg_1296_pp0_iter4_reg);

assign add01_1_fu_566_p2 = ($signed(sext_ln36_3_fu_562_p1) + $signed(sext_ln36_2_fu_558_p1));

assign add01_fu_300_p2 = ($signed(sext_ln36_1_fu_296_p1) + $signed(sext_ln36_fu_292_p1));

assign add03_1_fu_724_p2 = ($signed(sext_ln45_3_fu_721_p1) + $signed(sext_ln45_2_fu_718_p1));

assign add03_fu_676_p2 = ($signed(sext_ln45_1_fu_673_p1) + $signed(sext_ln45_fu_670_p1));

assign add07_1_fu_796_p2 = ($signed(sext_ln50_3_fu_793_p1) + $signed(sext_ln50_2_fu_790_p1));

assign add07_fu_772_p2 = ($signed(sext_ln50_1_fu_769_p1) + $signed(sext_ln50_fu_766_p1));

assign add0F_1_fu_842_p2 = ($signed(add8F_1_reg_1284) + $signed(add07_1_reg_1278));

assign add0F_fu_826_p2 = ($signed(add8F_reg_1272) + $signed(add07_reg_1266));

assign add23_1_fu_580_p2 = ($signed(sext_ln37_3_fu_576_p1) + $signed(sext_ln37_2_fu_572_p1));

assign add23_fu_314_p2 = ($signed(sext_ln37_1_fu_310_p1) + $signed(sext_ln37_fu_306_p1));

assign add45_1_fu_594_p2 = ($signed(sext_ln38_3_fu_590_p1) + $signed(sext_ln38_2_fu_586_p1));

assign add45_fu_328_p2 = ($signed(sext_ln38_1_fu_324_p1) + $signed(sext_ln38_fu_320_p1));

assign add47_1_fu_736_p2 = ($signed(sext_ln46_3_fu_733_p1) + $signed(sext_ln46_2_fu_730_p1));

assign add47_fu_688_p2 = ($signed(sext_ln46_1_fu_685_p1) + $signed(sext_ln46_fu_682_p1));

assign add67_1_fu_608_p2 = ($signed(sext_ln39_3_fu_604_p1) + $signed(sext_ln39_2_fu_600_p1));

assign add67_fu_342_p2 = ($signed(sext_ln39_1_fu_338_p1) + $signed(sext_ln39_fu_334_p1));

assign add89_1_fu_622_p2 = ($signed(sext_ln40_3_fu_618_p1) + $signed(sext_ln40_2_fu_614_p1));

assign add89_fu_356_p2 = ($signed(sext_ln40_1_fu_352_p1) + $signed(sext_ln40_fu_348_p1));

assign add8B_1_fu_748_p2 = ($signed(sext_ln47_3_fu_745_p1) + $signed(sext_ln47_2_fu_742_p1));

assign add8B_fu_700_p2 = ($signed(sext_ln47_1_fu_697_p1) + $signed(sext_ln47_fu_694_p1));

assign add8F_1_fu_808_p2 = ($signed(sext_ln51_3_fu_805_p1) + $signed(sext_ln51_2_fu_802_p1));

assign add8F_fu_784_p2 = ($signed(sext_ln51_1_fu_781_p1) + $signed(sext_ln51_fu_778_p1));

assign addAB_1_fu_636_p2 = ($signed(sext_ln41_3_fu_632_p1) + $signed(sext_ln41_2_fu_628_p1));

assign addAB_fu_370_p2 = ($signed(sext_ln41_1_fu_366_p1) + $signed(sext_ln41_fu_362_p1));

assign addCD_1_fu_650_p2 = ($signed(sext_ln42_3_fu_646_p1) + $signed(sext_ln42_2_fu_642_p1));

assign addCD_fu_384_p2 = ($signed(sext_ln42_1_fu_380_p1) + $signed(sext_ln42_fu_376_p1));

assign addCF_1_fu_760_p2 = ($signed(sext_ln48_3_fu_757_p1) + $signed(sext_ln48_2_fu_754_p1));

assign addCF_fu_712_p2 = ($signed(sext_ln48_1_fu_709_p1) + $signed(sext_ln48_fu_706_p1));

assign addEF_1_fu_664_p2 = ($signed(sext_ln43_3_fu_660_p1) + $signed(sext_ln43_2_fu_656_p1));

assign addEF_fu_398_p2 = ($signed(sext_ln43_1_fu_394_p1) + $signed(sext_ln43_fu_390_p1));

assign add_ln53_3_fu_836_p2 = ($signed(sext_ln53_3_fu_833_p1) + $signed(sext_ln53_2_fu_830_p1));

assign add_ln53_fu_820_p2 = ($signed(sext_ln53_1_fu_817_p1) + $signed(sext_ln53_fu_814_p1));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_return = grp_fu_1104_p2;

assign grp_fu_1044_p0 = {{m2_hl_reg_1465}, {18'd0}};

assign grp_fu_1044_p1 = l2_ml_reg_1470;

assign grp_fu_1060_p0 = {{m2_hl_1_reg_1480}, {18'd0}};

assign grp_fu_1060_p1 = l2_ml_1_reg_1485;

assign grp_fu_1076_p0 = {{h2_hm_reg_1460_pp0_iter14_reg}, {28'd0}};

assign grp_fu_1076_p1 = m2_hl_l2_ml_reg_1510;

assign grp_fu_1092_p0 = {{h2_hm_1_reg_1475_pp0_iter14_reg}, {28'd0}};

assign grp_fu_1092_p1 = m2_hl_l2_ml_1_reg_1515;

assign grp_fu_1104_p0 = h2_hm_m2_hl_l2_ml_reg_1540;

assign grp_fu_1104_p1 = h2_hm_m2_hl_l2_ml_1_reg_1545;

assign grp_fu_1110_p0 = zext_ln76_reg_1360_pp0_iter8_reg;

assign grp_fu_1110_p1 = zext_ln76_reg_1360_pp0_iter8_reg;

assign grp_fu_1110_p2 = grp_fu_1110_p20;

assign grp_fu_1110_p20 = shl_ln1_fu_991_p3;

assign grp_fu_1116_p0 = zext_ln77_reg_1368_pp0_iter8_reg;

assign grp_fu_1116_p1 = zext_ln77_reg_1368_pp0_iter8_reg;

assign grp_fu_1116_p2 = {{ml_reg_1410}, {10'd0}};

assign grp_fu_1122_p0 = zext_ln76_reg_1360_pp0_iter8_reg;

assign grp_fu_1122_p1 = zext_ln75_reg_1352_pp0_iter8_reg;

assign grp_fu_1122_p2 = {{h2_reg_1400}, {8'd0}};

assign grp_fu_1128_p0 = zext_ln76_1_reg_1384_pp0_iter8_reg;

assign grp_fu_1128_p1 = zext_ln76_1_reg_1384_pp0_iter8_reg;

assign grp_fu_1128_p2 = grp_fu_1128_p20;

assign grp_fu_1128_p20 = shl_ln83_1_fu_1016_p3;

assign grp_fu_1134_p0 = zext_ln77_1_reg_1392_pp0_iter8_reg;

assign grp_fu_1134_p1 = zext_ln77_1_reg_1392_pp0_iter8_reg;

assign grp_fu_1134_p2 = {{ml_1_reg_1425}, {10'd0}};

assign grp_fu_1140_p0 = zext_ln76_1_reg_1384_pp0_iter8_reg;

assign grp_fu_1140_p1 = zext_ln75_1_reg_1376_pp0_iter8_reg;

assign grp_fu_1140_p2 = {{h2_1_reg_1415}, {8'd0}};

assign grp_fu_933_p0 = zext_ln75_fu_930_p1;

assign grp_fu_933_p1 = zext_ln75_fu_930_p1;

assign grp_fu_945_p0 = zext_ln77_fu_942_p1;

assign grp_fu_945_p1 = zext_ln75_fu_930_p1;

assign grp_fu_951_p0 = zext_ln77_fu_942_p1;

assign grp_fu_951_p1 = grp_fu_951_p10;

assign grp_fu_951_p10 = medium_reg_1327;

assign grp_fu_960_p0 = zext_ln75_1_fu_957_p1;

assign grp_fu_960_p1 = zext_ln75_1_fu_957_p1;

assign grp_fu_972_p0 = zext_ln77_1_fu_969_p1;

assign grp_fu_972_p1 = zext_ln75_1_fu_957_p1;

assign grp_fu_978_p0 = zext_ln77_1_fu_969_p1;

assign grp_fu_978_p1 = grp_fu_978_p10;

assign grp_fu_978_p10 = medium_1_reg_1342;

assign low_1_fu_926_p1 = abs_old_0_in_fu_877_p3[8:0];

assign low_fu_902_p1 = abs_new_0_in_fu_872_p3[8:0];

assign mic_10_fu_232_p4 = {{data_new[263:240]}};

assign mic_11_fu_242_p4 = {{data_new[287:264]}};

assign mic_12_fu_252_p4 = {{data_new[311:288]}};

assign mic_13_fu_262_p4 = {{data_new[335:312]}};

assign mic_14_fu_272_p4 = {{data_new[359:336]}};

assign mic_15_fu_282_p4 = {{data_new[383:360]}};

assign mic_16_fu_404_p1 = data_old[23:0];

assign mic_17_fu_408_p4 = {{data_old[47:24]}};

assign mic_18_fu_418_p4 = {{data_old[71:48]}};

assign mic_19_fu_428_p4 = {{data_old[95:72]}};

assign mic_1_fu_142_p4 = {{data_new[47:24]}};

assign mic_20_fu_438_p4 = {{data_old[119:96]}};

assign mic_21_fu_448_p4 = {{data_old[143:120]}};

assign mic_22_fu_458_p4 = {{data_old[167:144]}};

assign mic_23_fu_468_p4 = {{data_old[191:168]}};

assign mic_24_fu_478_p4 = {{data_old[215:192]}};

assign mic_25_fu_488_p4 = {{data_old[239:216]}};

assign mic_26_fu_498_p4 = {{data_old[263:240]}};

assign mic_27_fu_508_p4 = {{data_old[287:264]}};

assign mic_28_fu_518_p4 = {{data_old[311:288]}};

assign mic_29_fu_528_p4 = {{data_old[335:312]}};

assign mic_2_fu_152_p4 = {{data_new[71:48]}};

assign mic_30_fu_538_p4 = {{data_old[359:336]}};

assign mic_31_fu_548_p4 = {{data_old[383:360]}};

assign mic_3_fu_162_p4 = {{data_new[95:72]}};

assign mic_4_fu_172_p4 = {{data_new[119:96]}};

assign mic_5_fu_182_p4 = {{data_new[143:120]}};

assign mic_6_fu_192_p4 = {{data_new[167:144]}};

assign mic_7_fu_202_p4 = {{data_new[191:168]}};

assign mic_8_fu_212_p4 = {{data_new[215:192]}};

assign mic_9_fu_222_p4 = {{data_new[239:216]}};

assign mic_fu_138_p1 = data_new[23:0];

assign sext_ln36_1_fu_296_p1 = $signed(mic_1_fu_142_p4);

assign sext_ln36_2_fu_558_p1 = $signed(mic_16_fu_404_p1);

assign sext_ln36_3_fu_562_p1 = $signed(mic_17_fu_408_p4);

assign sext_ln36_fu_292_p1 = $signed(mic_fu_138_p1);

assign sext_ln37_1_fu_310_p1 = $signed(mic_3_fu_162_p4);

assign sext_ln37_2_fu_572_p1 = $signed(mic_18_fu_418_p4);

assign sext_ln37_3_fu_576_p1 = $signed(mic_19_fu_428_p4);

assign sext_ln37_fu_306_p1 = $signed(mic_2_fu_152_p4);

assign sext_ln38_1_fu_324_p1 = $signed(mic_5_fu_182_p4);

assign sext_ln38_2_fu_586_p1 = $signed(mic_20_fu_438_p4);

assign sext_ln38_3_fu_590_p1 = $signed(mic_21_fu_448_p4);

assign sext_ln38_fu_320_p1 = $signed(mic_4_fu_172_p4);

assign sext_ln39_1_fu_338_p1 = $signed(mic_7_fu_202_p4);

assign sext_ln39_2_fu_600_p1 = $signed(mic_22_fu_458_p4);

assign sext_ln39_3_fu_604_p1 = $signed(mic_23_fu_468_p4);

assign sext_ln39_fu_334_p1 = $signed(mic_6_fu_192_p4);

assign sext_ln40_1_fu_352_p1 = $signed(mic_9_fu_222_p4);

assign sext_ln40_2_fu_614_p1 = $signed(mic_24_fu_478_p4);

assign sext_ln40_3_fu_618_p1 = $signed(mic_25_fu_488_p4);

assign sext_ln40_fu_348_p1 = $signed(mic_8_fu_212_p4);

assign sext_ln41_1_fu_366_p1 = $signed(mic_11_fu_242_p4);

assign sext_ln41_2_fu_628_p1 = $signed(mic_26_fu_498_p4);

assign sext_ln41_3_fu_632_p1 = $signed(mic_27_fu_508_p4);

assign sext_ln41_fu_362_p1 = $signed(mic_10_fu_232_p4);

assign sext_ln42_1_fu_380_p1 = $signed(mic_13_fu_262_p4);

assign sext_ln42_2_fu_642_p1 = $signed(mic_28_fu_518_p4);

assign sext_ln42_3_fu_646_p1 = $signed(mic_29_fu_528_p4);

assign sext_ln42_fu_376_p1 = $signed(mic_12_fu_252_p4);

assign sext_ln43_1_fu_394_p1 = $signed(mic_15_fu_282_p4);

assign sext_ln43_2_fu_656_p1 = $signed(mic_30_fu_538_p4);

assign sext_ln43_3_fu_660_p1 = $signed(mic_31_fu_548_p4);

assign sext_ln43_fu_390_p1 = $signed(mic_14_fu_272_p4);

assign sext_ln45_1_fu_673_p1 = $signed(add23_reg_1151);

assign sext_ln45_2_fu_718_p1 = $signed(add01_1_reg_1186);

assign sext_ln45_3_fu_721_p1 = $signed(add23_1_reg_1191);

assign sext_ln45_fu_670_p1 = $signed(add01_reg_1146);

assign sext_ln46_1_fu_685_p1 = $signed(add67_reg_1161);

assign sext_ln46_2_fu_730_p1 = $signed(add45_1_reg_1196);

assign sext_ln46_3_fu_733_p1 = $signed(add67_1_reg_1201);

assign sext_ln46_fu_682_p1 = $signed(add45_reg_1156);

assign sext_ln47_1_fu_697_p1 = $signed(addAB_reg_1171);

assign sext_ln47_2_fu_742_p1 = $signed(add89_1_reg_1206);

assign sext_ln47_3_fu_745_p1 = $signed(addAB_1_reg_1211);

assign sext_ln47_fu_694_p1 = $signed(add89_reg_1166);

assign sext_ln48_1_fu_709_p1 = $signed(addEF_reg_1181);

assign sext_ln48_2_fu_754_p1 = $signed(addCD_1_reg_1216);

assign sext_ln48_3_fu_757_p1 = $signed(addEF_1_reg_1221);

assign sext_ln48_fu_706_p1 = $signed(addCD_reg_1176);

assign sext_ln50_1_fu_769_p1 = $signed(add47_reg_1231);

assign sext_ln50_2_fu_790_p1 = $signed(add03_1_reg_1246);

assign sext_ln50_3_fu_793_p1 = $signed(add47_1_reg_1251);

assign sext_ln50_fu_766_p1 = $signed(add03_reg_1226);

assign sext_ln51_1_fu_781_p1 = $signed(addCF_reg_1241);

assign sext_ln51_2_fu_802_p1 = $signed(add8B_1_reg_1256);

assign sext_ln51_3_fu_805_p1 = $signed(addCF_1_reg_1261);

assign sext_ln51_fu_778_p1 = $signed(add8B_reg_1236);

assign sext_ln53_1_fu_817_p1 = add8F_reg_1272;

assign sext_ln53_2_fu_830_p1 = add07_1_reg_1278;

assign sext_ln53_3_fu_833_p1 = add8F_1_reg_1284;

assign sext_ln53_fu_814_p1 = add07_reg_1266;

assign shl_ln1_fu_991_p3 = {{hl_reg_1405}, {1'd0}};

assign shl_ln83_1_fu_1016_p3 = {{hl_1_reg_1420}, {1'd0}};

assign sub_ln61_1_fu_867_p2 = (27'd0 - add0F_1_reg_1296);

assign sub_ln61_fu_862_p2 = (27'd0 - add0F_reg_1290);

assign zext_ln75_1_fu_957_p1 = high_1_reg_1337;

assign zext_ln75_fu_930_p1 = high_reg_1322;

assign zext_ln76_1_fu_966_p1 = medium_1_reg_1342;

assign zext_ln76_fu_939_p1 = medium_reg_1327;

assign zext_ln77_1_fu_969_p1 = low_1_reg_1347;

assign zext_ln77_fu_942_p1 = low_reg_1332;

always @ (posedge ap_clk) begin
    zext_ln75_reg_1352[17:9] <= 9'b000000000;
    zext_ln75_reg_1352_pp0_iter7_reg[17:9] <= 9'b000000000;
    zext_ln75_reg_1352_pp0_iter8_reg[17:9] <= 9'b000000000;
    zext_ln76_reg_1360[17:9] <= 9'b000000000;
    zext_ln76_reg_1360_pp0_iter7_reg[17:9] <= 9'b000000000;
    zext_ln76_reg_1360_pp0_iter8_reg[17:9] <= 9'b000000000;
    zext_ln77_reg_1368[17:9] <= 9'b000000000;
    zext_ln77_reg_1368_pp0_iter7_reg[17:9] <= 9'b000000000;
    zext_ln77_reg_1368_pp0_iter8_reg[17:9] <= 9'b000000000;
    zext_ln75_1_reg_1376[17:9] <= 9'b000000000;
    zext_ln75_1_reg_1376_pp0_iter7_reg[17:9] <= 9'b000000000;
    zext_ln75_1_reg_1376_pp0_iter8_reg[17:9] <= 9'b000000000;
    zext_ln76_1_reg_1384[17:9] <= 9'b000000000;
    zext_ln76_1_reg_1384_pp0_iter7_reg[17:9] <= 9'b000000000;
    zext_ln76_1_reg_1384_pp0_iter8_reg[17:9] <= 9'b000000000;
    zext_ln77_1_reg_1392[17:9] <= 9'b000000000;
    zext_ln77_1_reg_1392_pp0_iter7_reg[17:9] <= 9'b000000000;
    zext_ln77_1_reg_1392_pp0_iter8_reg[17:9] <= 9'b000000000;
end

endmodule //calculate
