// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module add_image_Loop_loop_height_proc14 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        CAM_STREAM_TDATA,
        CAM_STREAM_TVALID,
        CAM_STREAM_TREADY,
        CAM_STREAM_TKEEP,
        CAM_STREAM_TSTRB,
        CAM_STREAM_TUSER,
        CAM_STREAM_TLAST,
        CAM_STREAM_TID,
        CAM_STREAM_TDEST,
        camImg_data_din,
        camImg_data_num_data_valid,
        camImg_data_fifo_cap,
        camImg_data_full_n,
        camImg_data_write
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] CAM_STREAM_TDATA;
input   CAM_STREAM_TVALID;
output   CAM_STREAM_TREADY;
input  [2:0] CAM_STREAM_TKEEP;
input  [2:0] CAM_STREAM_TSTRB;
input  [0:0] CAM_STREAM_TUSER;
input  [0:0] CAM_STREAM_TLAST;
input  [0:0] CAM_STREAM_TID;
input  [0:0] CAM_STREAM_TDEST;
output  [23:0] camImg_data_din;
input  [2:0] camImg_data_num_data_valid;
input  [2:0] camImg_data_fifo_cap;
input   camImg_data_full_n;
output   camImg_data_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg camImg_data_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] start_1_load_reg_172;
wire    ap_CS_fsm_state2;
wire    grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_ap_start;
wire    grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_ap_done;
wire    grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_ap_idle;
wire    grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_ap_ready;
wire   [23:0] grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_camImg_data_din;
wire    grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_camImg_data_write;
wire    grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_CAM_STREAM_TREADY;
wire   [31:0] grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_start_3_out;
wire    grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_start_3_out_ap_vld;
wire   [0:0] grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_eol_2_out;
wire    grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_eol_2_out_ap_vld;
wire    grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93_ap_start;
wire    grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93_ap_done;
wire    grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93_ap_idle;
wire    grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93_ap_ready;
wire    grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93_CAM_STREAM_TREADY;
reg    grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_ap_start_reg;
reg   [6:0] ap_NS_fsm;
wire    ap_NS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [31:0] start_1_fu_58;
reg    grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    ap_block_state1;
wire   [0:0] icmp_ln119_fu_125_p2;
reg   [9:0] i_2_fu_62;
wire   [9:0] i_5_fu_131_p2;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    regslice_both_CAM_STREAM_V_data_V_U_apdone_blk;
wire   [23:0] CAM_STREAM_TDATA_int_regslice;
wire    CAM_STREAM_TVALID_int_regslice;
reg    CAM_STREAM_TREADY_int_regslice;
wire    regslice_both_CAM_STREAM_V_data_V_U_ack_in;
wire    regslice_both_CAM_STREAM_V_keep_V_U_apdone_blk;
wire   [2:0] CAM_STREAM_TKEEP_int_regslice;
wire    regslice_both_CAM_STREAM_V_keep_V_U_vld_out;
wire    regslice_both_CAM_STREAM_V_keep_V_U_ack_in;
wire    regslice_both_CAM_STREAM_V_strb_V_U_apdone_blk;
wire   [2:0] CAM_STREAM_TSTRB_int_regslice;
wire    regslice_both_CAM_STREAM_V_strb_V_U_vld_out;
wire    regslice_both_CAM_STREAM_V_strb_V_U_ack_in;
wire    regslice_both_CAM_STREAM_V_user_V_U_apdone_blk;
wire   [0:0] CAM_STREAM_TUSER_int_regslice;
wire    regslice_both_CAM_STREAM_V_user_V_U_vld_out;
wire    regslice_both_CAM_STREAM_V_user_V_U_ack_in;
wire    regslice_both_CAM_STREAM_V_last_V_U_apdone_blk;
wire   [0:0] CAM_STREAM_TLAST_int_regslice;
wire    regslice_both_CAM_STREAM_V_last_V_U_vld_out;
wire    regslice_both_CAM_STREAM_V_last_V_U_ack_in;
wire    regslice_both_CAM_STREAM_V_id_V_U_apdone_blk;
wire   [0:0] CAM_STREAM_TID_int_regslice;
wire    regslice_both_CAM_STREAM_V_id_V_U_vld_out;
wire    regslice_both_CAM_STREAM_V_id_V_U_ack_in;
wire    regslice_both_CAM_STREAM_V_dest_V_U_apdone_blk;
wire   [0:0] CAM_STREAM_TDEST_int_regslice;
wire    regslice_both_CAM_STREAM_V_dest_V_U_vld_out;
wire    regslice_both_CAM_STREAM_V_dest_V_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 7'd1;
#0 grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_ap_start_reg = 1'b0;
#0 start_1_fu_58 = 32'd0;
#0 grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93_ap_start_reg = 1'b0;
#0 i_2_fu_62 = 10'd0;
end

add_image_Loop_loop_height_proc14_Pipeline_loop_width grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_ap_start),
    .ap_done(grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_ap_done),
    .ap_idle(grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_ap_idle),
    .ap_ready(grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_ap_ready),
    .CAM_STREAM_TVALID(CAM_STREAM_TVALID_int_regslice),
    .camImg_data_din(grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_camImg_data_din),
    .camImg_data_num_data_valid(3'd0),
    .camImg_data_fifo_cap(3'd0),
    .camImg_data_full_n(camImg_data_full_n),
    .camImg_data_write(grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_camImg_data_write),
    .start_1(start_1_load_reg_172),
    .CAM_STREAM_TDATA(CAM_STREAM_TDATA_int_regslice),
    .CAM_STREAM_TREADY(grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_CAM_STREAM_TREADY),
    .CAM_STREAM_TKEEP(CAM_STREAM_TKEEP_int_regslice),
    .CAM_STREAM_TSTRB(CAM_STREAM_TSTRB_int_regslice),
    .CAM_STREAM_TUSER(CAM_STREAM_TUSER_int_regslice),
    .CAM_STREAM_TLAST(CAM_STREAM_TLAST_int_regslice),
    .CAM_STREAM_TID(CAM_STREAM_TID_int_regslice),
    .CAM_STREAM_TDEST(CAM_STREAM_TDEST_int_regslice),
    .start_3_out(grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_start_3_out),
    .start_3_out_ap_vld(grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_start_3_out_ap_vld),
    .eol_2_out(grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_eol_2_out),
    .eol_2_out_ap_vld(grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_eol_2_out_ap_vld)
);

add_image_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93_ap_start),
    .ap_done(grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93_ap_done),
    .ap_idle(grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93_ap_idle),
    .ap_ready(grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93_ap_ready),
    .CAM_STREAM_TVALID(CAM_STREAM_TVALID_int_regslice),
    .eol_2_reload(grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_eol_2_out),
    .CAM_STREAM_TDATA(CAM_STREAM_TDATA_int_regslice),
    .CAM_STREAM_TREADY(grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93_CAM_STREAM_TREADY),
    .CAM_STREAM_TKEEP(CAM_STREAM_TKEEP_int_regslice),
    .CAM_STREAM_TSTRB(CAM_STREAM_TSTRB_int_regslice),
    .CAM_STREAM_TUSER(CAM_STREAM_TUSER_int_regslice),
    .CAM_STREAM_TLAST(CAM_STREAM_TLAST_int_regslice),
    .CAM_STREAM_TID(CAM_STREAM_TID_int_regslice),
    .CAM_STREAM_TDEST(CAM_STREAM_TDEST_int_regslice)
);

add_image_regslice_both #(
    .DataWidth( 24 ))
regslice_both_CAM_STREAM_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(CAM_STREAM_TDATA),
    .vld_in(CAM_STREAM_TVALID),
    .ack_in(regslice_both_CAM_STREAM_V_data_V_U_ack_in),
    .data_out(CAM_STREAM_TDATA_int_regslice),
    .vld_out(CAM_STREAM_TVALID_int_regslice),
    .ack_out(CAM_STREAM_TREADY_int_regslice),
    .apdone_blk(regslice_both_CAM_STREAM_V_data_V_U_apdone_blk)
);

add_image_regslice_both #(
    .DataWidth( 3 ))
regslice_both_CAM_STREAM_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(CAM_STREAM_TKEEP),
    .vld_in(CAM_STREAM_TVALID),
    .ack_in(regslice_both_CAM_STREAM_V_keep_V_U_ack_in),
    .data_out(CAM_STREAM_TKEEP_int_regslice),
    .vld_out(regslice_both_CAM_STREAM_V_keep_V_U_vld_out),
    .ack_out(CAM_STREAM_TREADY_int_regslice),
    .apdone_blk(regslice_both_CAM_STREAM_V_keep_V_U_apdone_blk)
);

add_image_regslice_both #(
    .DataWidth( 3 ))
regslice_both_CAM_STREAM_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(CAM_STREAM_TSTRB),
    .vld_in(CAM_STREAM_TVALID),
    .ack_in(regslice_both_CAM_STREAM_V_strb_V_U_ack_in),
    .data_out(CAM_STREAM_TSTRB_int_regslice),
    .vld_out(regslice_both_CAM_STREAM_V_strb_V_U_vld_out),
    .ack_out(CAM_STREAM_TREADY_int_regslice),
    .apdone_blk(regslice_both_CAM_STREAM_V_strb_V_U_apdone_blk)
);

add_image_regslice_both #(
    .DataWidth( 1 ))
regslice_both_CAM_STREAM_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(CAM_STREAM_TUSER),
    .vld_in(CAM_STREAM_TVALID),
    .ack_in(regslice_both_CAM_STREAM_V_user_V_U_ack_in),
    .data_out(CAM_STREAM_TUSER_int_regslice),
    .vld_out(regslice_both_CAM_STREAM_V_user_V_U_vld_out),
    .ack_out(CAM_STREAM_TREADY_int_regslice),
    .apdone_blk(regslice_both_CAM_STREAM_V_user_V_U_apdone_blk)
);

add_image_regslice_both #(
    .DataWidth( 1 ))
regslice_both_CAM_STREAM_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(CAM_STREAM_TLAST),
    .vld_in(CAM_STREAM_TVALID),
    .ack_in(regslice_both_CAM_STREAM_V_last_V_U_ack_in),
    .data_out(CAM_STREAM_TLAST_int_regslice),
    .vld_out(regslice_both_CAM_STREAM_V_last_V_U_vld_out),
    .ack_out(CAM_STREAM_TREADY_int_regslice),
    .apdone_blk(regslice_both_CAM_STREAM_V_last_V_U_apdone_blk)
);

add_image_regslice_both #(
    .DataWidth( 1 ))
regslice_both_CAM_STREAM_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(CAM_STREAM_TID),
    .vld_in(CAM_STREAM_TVALID),
    .ack_in(regslice_both_CAM_STREAM_V_id_V_U_ack_in),
    .data_out(CAM_STREAM_TID_int_regslice),
    .vld_out(regslice_both_CAM_STREAM_V_id_V_U_vld_out),
    .ack_out(CAM_STREAM_TREADY_int_regslice),
    .apdone_blk(regslice_both_CAM_STREAM_V_id_V_U_apdone_blk)
);

add_image_regslice_both #(
    .DataWidth( 1 ))
regslice_both_CAM_STREAM_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(CAM_STREAM_TDEST),
    .vld_in(CAM_STREAM_TVALID),
    .ack_in(regslice_both_CAM_STREAM_V_dest_V_U_ack_in),
    .data_out(CAM_STREAM_TDEST_int_regslice),
    .vld_out(regslice_both_CAM_STREAM_V_dest_V_U_vld_out),
    .ack_out(CAM_STREAM_TREADY_int_regslice),
    .apdone_blk(regslice_both_CAM_STREAM_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln119_fu_125_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93_ap_start_reg <= 1'b1;
        end else if ((grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93_ap_ready == 1'b1)) begin
            grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state3) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_ap_start_reg <= 1'b1;
        end else if ((grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_ap_ready == 1'b1)) begin
            grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        i_2_fu_62 <= 10'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln119_fu_125_p2 == 1'd0))) begin
        i_2_fu_62 <= i_5_fu_131_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        start_1_fu_58 <= 32'd0;
    end else if (((grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_start_3_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        start_1_fu_58 <= grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_start_3_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        start_1_load_reg_172 <= start_1_fu_58;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        CAM_STREAM_TREADY_int_regslice = grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93_CAM_STREAM_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        CAM_STREAM_TREADY_int_regslice = grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_CAM_STREAM_TREADY;
    end else begin
        CAM_STREAM_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln119_fu_125_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln119_fu_125_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        camImg_data_write = grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_camImg_data_write;
    end else begin
        camImg_data_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln119_fu_125_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign CAM_STREAM_TREADY = regslice_both_CAM_STREAM_V_data_V_U_ack_in;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_NS_fsm_state3 = ap_NS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign camImg_data_din = grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_camImg_data_din;

assign grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93_ap_start = grp_Loop_loop_height_proc14_Pipeline_loop_wait_for_eol_fu_93_ap_start_reg;

assign grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_ap_start = grp_Loop_loop_height_proc14_Pipeline_loop_width_fu_70_ap_start_reg;

assign i_5_fu_131_p2 = (i_2_fu_62 + 10'd1);

assign icmp_ln119_fu_125_p2 = ((i_2_fu_62 == 10'd720) ? 1'b1 : 1'b0);

endmodule //add_image_Loop_loop_height_proc14
