// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="delay_delay,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-2,HLS_INPUT_CLOCK=2.778000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=1.546000,HLS_SYN_LAT=11,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1976,HLS_SYN_LUT=1526,HLS_VERSION=2024_1}" *)

module delay (
        ap_clk,
        ap_rst,
        addrs_signed,
        now,
        addrs_left,
        rates_left,
        addrs_right,
        rates_right
);


input   ap_clk;
input   ap_rst;
input  [39:0] addrs_signed;
input  [11:0] now;
output  [191:0] addrs_left;
output  [79:0] rates_left;
output  [191:0] addrs_right;
output  [95:0] rates_right;

reg   [11:0] now_read_reg_1193;
wire    ap_block_pp0_stage0_11001;
reg   [11:0] now_read_reg_1193_pp0_iter1_reg;
reg   [11:0] now_read_reg_1193_pp0_iter2_reg;
reg   [11:0] now_read_reg_1193_pp0_iter3_reg;
reg   [11:0] now_read_reg_1193_pp0_iter4_reg;
reg   [11:0] now_read_reg_1193_pp0_iter5_reg;
reg   [11:0] now_read_reg_1193_pp0_iter6_reg;
reg   [11:0] now_read_reg_1193_pp0_iter7_reg;
reg   [11:0] now_read_reg_1193_pp0_iter8_reg;
reg   [11:0] now_read_reg_1193_pp0_iter9_reg;
wire   [9:0] addr_signed_fu_128_p4;
reg   [9:0] addr_signed_reg_1213;
reg   [9:0] addr_signed_reg_1213_pp0_iter1_reg;
reg   [9:0] addr_signed_reg_1213_pp0_iter2_reg;
reg   [9:0] addr_signed_reg_1213_pp0_iter3_reg;
reg   [9:0] addr_signed_reg_1213_pp0_iter4_reg;
reg   [9:0] addr_signed_reg_1213_pp0_iter5_reg;
reg   [9:0] addr_signed_reg_1213_pp0_iter6_reg;
reg   [9:0] addr_signed_reg_1213_pp0_iter7_reg;
reg   [9:0] addr_signed_reg_1213_pp0_iter8_reg;
wire   [9:0] addr_signed_1_fu_138_p4;
reg   [9:0] addr_signed_1_reg_1220;
reg   [9:0] addr_signed_1_reg_1220_pp0_iter1_reg;
reg   [9:0] addr_signed_1_reg_1220_pp0_iter2_reg;
reg   [9:0] addr_signed_1_reg_1220_pp0_iter3_reg;
reg   [9:0] addr_signed_1_reg_1220_pp0_iter4_reg;
reg   [9:0] addr_signed_1_reg_1220_pp0_iter5_reg;
reg   [9:0] addr_signed_1_reg_1220_pp0_iter6_reg;
reg   [9:0] addr_signed_1_reg_1220_pp0_iter7_reg;
reg   [9:0] addr_signed_1_reg_1220_pp0_iter8_reg;
wire   [9:0] addr_signed_2_fu_148_p4;
reg   [9:0] addr_signed_2_reg_1227;
reg   [9:0] addr_signed_2_reg_1227_pp0_iter1_reg;
reg   [9:0] addr_signed_2_reg_1227_pp0_iter2_reg;
reg   [9:0] addr_signed_2_reg_1227_pp0_iter3_reg;
reg   [9:0] addr_signed_2_reg_1227_pp0_iter4_reg;
reg   [9:0] addr_signed_2_reg_1227_pp0_iter5_reg;
reg   [9:0] addr_signed_2_reg_1227_pp0_iter6_reg;
reg   [9:0] addr_signed_2_reg_1227_pp0_iter7_reg;
reg   [9:0] addr_signed_2_reg_1227_pp0_iter8_reg;
wire   [9:0] addr_signed_3_fu_158_p1;
reg   [9:0] addr_signed_3_reg_1234;
reg   [9:0] addr_signed_3_reg_1234_pp0_iter1_reg;
reg   [9:0] addr_signed_3_reg_1234_pp0_iter2_reg;
reg   [9:0] addr_signed_3_reg_1234_pp0_iter3_reg;
reg   [9:0] addr_signed_3_reg_1234_pp0_iter4_reg;
reg   [9:0] addr_signed_3_reg_1234_pp0_iter5_reg;
reg   [9:0] addr_signed_3_reg_1234_pp0_iter6_reg;
reg   [9:0] addr_signed_3_reg_1234_pp0_iter7_reg;
reg   [9:0] addr_signed_3_reg_1234_pp0_iter8_reg;
wire   [9:0] addr_signed_4_fu_162_p2;
reg   [9:0] addr_signed_4_reg_1241;
reg   [9:0] addr_signed_4_reg_1241_pp0_iter1_reg;
reg   [9:0] addr_signed_4_reg_1241_pp0_iter2_reg;
reg   [9:0] addr_signed_4_reg_1241_pp0_iter3_reg;
reg   [9:0] addr_signed_4_reg_1241_pp0_iter4_reg;
reg   [9:0] addr_signed_4_reg_1241_pp0_iter5_reg;
reg   [9:0] addr_signed_4_reg_1241_pp0_iter6_reg;
reg   [9:0] addr_signed_4_reg_1241_pp0_iter7_reg;
reg   [9:0] addr_signed_4_reg_1241_pp0_iter8_reg;
wire   [9:0] addr_signed_5_fu_168_p2;
reg   [9:0] addr_signed_5_reg_1248;
reg   [9:0] addr_signed_5_reg_1248_pp0_iter1_reg;
reg   [9:0] addr_signed_5_reg_1248_pp0_iter2_reg;
reg   [9:0] addr_signed_5_reg_1248_pp0_iter3_reg;
reg   [9:0] addr_signed_5_reg_1248_pp0_iter4_reg;
reg   [9:0] addr_signed_5_reg_1248_pp0_iter5_reg;
reg   [9:0] addr_signed_5_reg_1248_pp0_iter6_reg;
reg   [9:0] addr_signed_5_reg_1248_pp0_iter7_reg;
reg   [9:0] addr_signed_5_reg_1248_pp0_iter8_reg;
wire   [9:0] addr_signed_6_fu_174_p2;
reg   [9:0] addr_signed_6_reg_1255;
reg   [9:0] addr_signed_6_reg_1255_pp0_iter1_reg;
reg   [9:0] addr_signed_6_reg_1255_pp0_iter2_reg;
reg   [9:0] addr_signed_6_reg_1255_pp0_iter3_reg;
reg   [9:0] addr_signed_6_reg_1255_pp0_iter4_reg;
reg   [9:0] addr_signed_6_reg_1255_pp0_iter5_reg;
reg   [9:0] addr_signed_6_reg_1255_pp0_iter6_reg;
reg   [9:0] addr_signed_6_reg_1255_pp0_iter7_reg;
reg   [9:0] addr_signed_6_reg_1255_pp0_iter8_reg;
wire   [9:0] addr_signed_7_fu_180_p2;
reg   [9:0] addr_signed_7_reg_1262;
reg   [9:0] addr_signed_7_reg_1262_pp0_iter1_reg;
reg   [9:0] addr_signed_7_reg_1262_pp0_iter2_reg;
reg   [9:0] addr_signed_7_reg_1262_pp0_iter3_reg;
reg   [9:0] addr_signed_7_reg_1262_pp0_iter4_reg;
reg   [9:0] addr_signed_7_reg_1262_pp0_iter5_reg;
reg   [9:0] addr_signed_7_reg_1262_pp0_iter6_reg;
reg   [9:0] addr_signed_7_reg_1262_pp0_iter7_reg;
reg   [9:0] addr_signed_7_reg_1262_pp0_iter8_reg;
reg  signed [8:0] addr_signed_8_reg_1269;
reg  signed [8:0] addr_signed_8_reg_1269_pp0_iter1_reg;
reg  signed [8:0] addr_signed_8_reg_1269_pp0_iter2_reg;
reg  signed [8:0] addr_signed_8_reg_1269_pp0_iter3_reg;
reg  signed [8:0] addr_signed_8_reg_1269_pp0_iter4_reg;
reg  signed [8:0] addr_signed_8_reg_1269_pp0_iter5_reg;
reg  signed [8:0] addr_signed_8_reg_1269_pp0_iter6_reg;
reg  signed [8:0] addr_signed_8_reg_1269_pp0_iter7_reg;
reg  signed [8:0] addr_signed_8_reg_1269_pp0_iter8_reg;
reg  signed [8:0] addr_signed_9_reg_1276;
reg  signed [8:0] addr_signed_9_reg_1276_pp0_iter1_reg;
reg  signed [8:0] addr_signed_9_reg_1276_pp0_iter2_reg;
reg  signed [8:0] addr_signed_9_reg_1276_pp0_iter3_reg;
reg  signed [8:0] addr_signed_9_reg_1276_pp0_iter4_reg;
reg  signed [8:0] addr_signed_9_reg_1276_pp0_iter5_reg;
reg  signed [8:0] addr_signed_9_reg_1276_pp0_iter6_reg;
reg  signed [8:0] addr_signed_9_reg_1276_pp0_iter7_reg;
reg  signed [8:0] addr_signed_9_reg_1276_pp0_iter8_reg;
reg  signed [8:0] addr_signed_10_reg_1283;
reg  signed [8:0] addr_signed_10_reg_1283_pp0_iter1_reg;
reg  signed [8:0] addr_signed_10_reg_1283_pp0_iter2_reg;
reg  signed [8:0] addr_signed_10_reg_1283_pp0_iter3_reg;
reg  signed [8:0] addr_signed_10_reg_1283_pp0_iter4_reg;
reg  signed [8:0] addr_signed_10_reg_1283_pp0_iter5_reg;
reg  signed [8:0] addr_signed_10_reg_1283_pp0_iter6_reg;
reg  signed [8:0] addr_signed_10_reg_1283_pp0_iter7_reg;
reg  signed [8:0] addr_signed_10_reg_1283_pp0_iter8_reg;
reg  signed [8:0] addr_signed_11_reg_1290;
reg  signed [8:0] addr_signed_11_reg_1290_pp0_iter1_reg;
reg  signed [8:0] addr_signed_11_reg_1290_pp0_iter2_reg;
reg  signed [8:0] addr_signed_11_reg_1290_pp0_iter3_reg;
reg  signed [8:0] addr_signed_11_reg_1290_pp0_iter4_reg;
reg  signed [8:0] addr_signed_11_reg_1290_pp0_iter5_reg;
reg  signed [8:0] addr_signed_11_reg_1290_pp0_iter6_reg;
reg  signed [8:0] addr_signed_11_reg_1290_pp0_iter7_reg;
reg  signed [8:0] addr_signed_11_reg_1290_pp0_iter8_reg;
reg  signed [8:0] addr_signed_12_reg_1297;
reg  signed [8:0] addr_signed_12_reg_1297_pp0_iter1_reg;
reg  signed [8:0] addr_signed_12_reg_1297_pp0_iter2_reg;
reg  signed [8:0] addr_signed_12_reg_1297_pp0_iter3_reg;
reg  signed [8:0] addr_signed_12_reg_1297_pp0_iter4_reg;
reg  signed [8:0] addr_signed_12_reg_1297_pp0_iter5_reg;
reg  signed [8:0] addr_signed_12_reg_1297_pp0_iter6_reg;
reg  signed [8:0] addr_signed_12_reg_1297_pp0_iter7_reg;
reg  signed [8:0] addr_signed_12_reg_1297_pp0_iter8_reg;
reg  signed [8:0] addr_signed_13_reg_1304;
reg  signed [8:0] addr_signed_13_reg_1304_pp0_iter1_reg;
reg  signed [8:0] addr_signed_13_reg_1304_pp0_iter2_reg;
reg  signed [8:0] addr_signed_13_reg_1304_pp0_iter3_reg;
reg  signed [8:0] addr_signed_13_reg_1304_pp0_iter4_reg;
reg  signed [8:0] addr_signed_13_reg_1304_pp0_iter5_reg;
reg  signed [8:0] addr_signed_13_reg_1304_pp0_iter6_reg;
reg  signed [8:0] addr_signed_13_reg_1304_pp0_iter7_reg;
reg  signed [8:0] addr_signed_13_reg_1304_pp0_iter8_reg;
reg  signed [8:0] addr_signed_14_reg_1311;
reg  signed [8:0] addr_signed_14_reg_1311_pp0_iter1_reg;
reg  signed [8:0] addr_signed_14_reg_1311_pp0_iter2_reg;
reg  signed [8:0] addr_signed_14_reg_1311_pp0_iter3_reg;
reg  signed [8:0] addr_signed_14_reg_1311_pp0_iter4_reg;
reg  signed [8:0] addr_signed_14_reg_1311_pp0_iter5_reg;
reg  signed [8:0] addr_signed_14_reg_1311_pp0_iter6_reg;
reg  signed [8:0] addr_signed_14_reg_1311_pp0_iter7_reg;
reg  signed [8:0] addr_signed_14_reg_1311_pp0_iter8_reg;
reg  signed [8:0] addr_signed_15_reg_1318;
reg  signed [8:0] addr_signed_15_reg_1318_pp0_iter1_reg;
reg  signed [8:0] addr_signed_15_reg_1318_pp0_iter2_reg;
reg  signed [8:0] addr_signed_15_reg_1318_pp0_iter3_reg;
reg  signed [8:0] addr_signed_15_reg_1318_pp0_iter4_reg;
reg  signed [8:0] addr_signed_15_reg_1318_pp0_iter5_reg;
reg  signed [8:0] addr_signed_15_reg_1318_pp0_iter6_reg;
reg  signed [8:0] addr_signed_15_reg_1318_pp0_iter7_reg;
reg  signed [8:0] addr_signed_15_reg_1318_pp0_iter8_reg;
wire   [0:0] icmp_ln247_fu_266_p2;
reg   [0:0] icmp_ln247_reg_1325;
wire   [0:0] icmp_ln247_1_fu_270_p2;
reg   [0:0] icmp_ln247_1_reg_1330;
wire   [0:0] icmp_ln247_2_fu_274_p2;
reg   [0:0] icmp_ln247_2_reg_1335;
wire   [0:0] icmp_ln247_3_fu_278_p2;
reg   [0:0] icmp_ln247_3_reg_1340;
wire   [0:0] icmp_ln247_4_fu_282_p2;
reg   [0:0] icmp_ln247_4_reg_1345;
wire   [0:0] icmp_ln247_5_fu_286_p2;
reg   [0:0] icmp_ln247_5_reg_1350;
wire   [0:0] icmp_ln247_6_fu_290_p2;
reg   [0:0] icmp_ln247_6_reg_1355;
wire   [0:0] icmp_ln247_7_fu_294_p2;
reg   [0:0] icmp_ln247_7_reg_1360;
wire   [9:0] min01_fu_298_p3;
reg   [9:0] min01_reg_1365;
reg   [9:0] min01_reg_1365_pp0_iter3_reg;
wire   [9:0] min23_fu_303_p3;
reg   [9:0] min23_reg_1371;
reg   [9:0] min23_reg_1371_pp0_iter3_reg;
wire   [9:0] min45_fu_308_p3;
reg   [9:0] min45_reg_1377;
reg   [9:0] min45_reg_1377_pp0_iter3_reg;
wire   [9:0] min67_fu_313_p3;
reg   [9:0] min67_reg_1383;
reg   [9:0] min67_reg_1383_pp0_iter3_reg;
wire   [8:0] select_ln247_fu_318_p3;
reg   [8:0] select_ln247_reg_1389;
reg   [8:0] select_ln247_reg_1389_pp0_iter3_reg;
wire   [8:0] select_ln247_1_fu_323_p3;
reg   [8:0] select_ln247_1_reg_1395;
reg   [8:0] select_ln247_1_reg_1395_pp0_iter3_reg;
wire   [8:0] select_ln247_2_fu_328_p3;
reg   [8:0] select_ln247_2_reg_1401;
reg   [8:0] select_ln247_2_reg_1401_pp0_iter3_reg;
wire   [8:0] select_ln247_3_fu_333_p3;
reg   [8:0] select_ln247_3_reg_1407;
reg   [8:0] select_ln247_3_reg_1407_pp0_iter3_reg;
wire   [0:0] icmp_ln247_8_fu_338_p2;
reg   [0:0] icmp_ln247_8_reg_1413;
wire   [0:0] icmp_ln247_9_fu_342_p2;
reg   [0:0] icmp_ln247_9_reg_1418;
wire   [0:0] icmp_ln247_10_fu_346_p2;
reg   [0:0] icmp_ln247_10_reg_1423;
wire   [0:0] icmp_ln247_11_fu_350_p2;
reg   [0:0] icmp_ln247_11_reg_1428;
wire   [9:0] min03_fu_354_p3;
reg   [9:0] min03_reg_1433;
reg   [9:0] min03_reg_1433_pp0_iter5_reg;
wire   [9:0] min47_fu_359_p3;
reg   [9:0] min47_reg_1439;
reg   [9:0] min47_reg_1439_pp0_iter5_reg;
wire   [8:0] select_ln247_6_fu_364_p3;
reg   [8:0] select_ln247_6_reg_1445;
reg   [8:0] select_ln247_6_reg_1445_pp0_iter5_reg;
wire   [8:0] select_ln247_7_fu_369_p3;
reg   [8:0] select_ln247_7_reg_1451;
reg   [8:0] select_ln247_7_reg_1451_pp0_iter5_reg;
wire   [0:0] icmp_ln247_12_fu_374_p2;
reg   [0:0] icmp_ln247_12_reg_1457;
wire   [0:0] icmp_ln247_13_fu_378_p2;
reg   [0:0] icmp_ln247_13_reg_1462;
wire   [9:0] min07_fu_382_p3;
reg   [9:0] min07_reg_1467;
reg   [9:0] min07_reg_1467_pp0_iter7_reg;
wire   [8:0] min8F_fu_387_p3;
reg   [8:0] min8F_reg_1473;
wire  signed [9:0] sext_ln247_fu_392_p1;
reg  signed [9:0] sext_ln247_reg_1478;
wire   [0:0] icmp_ln247_14_fu_395_p2;
reg   [0:0] icmp_ln247_14_reg_1483;
wire   [9:0] min_value_fu_400_p3;
reg   [9:0] min_value_reg_1488;
reg   [4:0] tmp8_reg_1508;
wire   [4:0] rate_left_fu_443_p1;
reg   [4:0] rate_left_reg_1513;
reg   [4:0] rate_left_reg_1513_pp0_iter10_reg;
reg   [4:0] tmp_s_reg_1519;
wire   [4:0] rate_left_1_fu_461_p1;
reg   [4:0] rate_left_1_reg_1524;
reg   [4:0] rate_left_1_reg_1524_pp0_iter10_reg;
reg   [4:0] tmp_1_reg_1530;
wire   [4:0] rate_left_2_fu_479_p1;
reg   [4:0] rate_left_2_reg_1535;
reg   [4:0] rate_left_2_reg_1535_pp0_iter10_reg;
reg   [4:0] tmp_2_reg_1541;
wire   [4:0] rate_left_3_fu_497_p1;
reg   [4:0] rate_left_3_reg_1546;
reg   [4:0] rate_left_3_reg_1546_pp0_iter10_reg;
reg   [4:0] tmp_3_reg_1552;
wire   [4:0] rate_left_4_fu_515_p1;
reg   [4:0] rate_left_4_reg_1557;
reg   [4:0] rate_left_4_reg_1557_pp0_iter10_reg;
reg   [4:0] tmp_4_reg_1563;
wire   [4:0] rate_left_5_fu_533_p1;
reg   [4:0] rate_left_5_reg_1568;
reg   [4:0] rate_left_5_reg_1568_pp0_iter10_reg;
reg   [4:0] tmp_5_reg_1574;
wire   [4:0] rate_left_6_fu_551_p1;
reg   [4:0] rate_left_6_reg_1579;
reg   [4:0] rate_left_6_reg_1579_pp0_iter10_reg;
reg   [4:0] tmp_6_reg_1585;
wire   [4:0] rate_left_7_fu_569_p1;
reg   [4:0] rate_left_7_reg_1590;
reg   [4:0] rate_left_7_reg_1590_pp0_iter10_reg;
reg   [4:0] tmp_7_reg_1596;
wire   [4:0] rate_left_8_fu_588_p1;
reg   [4:0] rate_left_8_reg_1601;
reg   [4:0] rate_left_8_reg_1601_pp0_iter10_reg;
reg   [4:0] tmp_8_reg_1607;
wire   [4:0] rate_left_9_fu_607_p1;
reg   [4:0] rate_left_9_reg_1612;
reg   [4:0] rate_left_9_reg_1612_pp0_iter10_reg;
reg   [4:0] tmp_9_reg_1618;
wire   [4:0] rate_left_10_fu_626_p1;
reg   [4:0] rate_left_10_reg_1623;
reg   [4:0] rate_left_10_reg_1623_pp0_iter10_reg;
reg   [4:0] tmp_10_reg_1629;
wire   [4:0] rate_left_11_fu_645_p1;
reg   [4:0] rate_left_11_reg_1634;
reg   [4:0] rate_left_11_reg_1634_pp0_iter10_reg;
reg   [4:0] tmp_11_reg_1640;
wire   [4:0] rate_left_12_fu_664_p1;
reg   [4:0] rate_left_12_reg_1645;
reg   [4:0] rate_left_12_reg_1645_pp0_iter10_reg;
reg   [4:0] tmp_12_reg_1651;
wire   [4:0] rate_left_13_fu_683_p1;
reg   [4:0] rate_left_13_reg_1656;
reg   [4:0] rate_left_13_reg_1656_pp0_iter10_reg;
reg   [4:0] tmp_13_reg_1662;
wire   [4:0] rate_left_14_fu_702_p1;
reg   [4:0] rate_left_14_reg_1667;
reg   [4:0] rate_left_14_reg_1667_pp0_iter10_reg;
reg   [4:0] tmp_14_reg_1673;
wire   [4:0] rate_left_15_fu_721_p1;
reg   [4:0] rate_left_15_reg_1678;
reg   [4:0] rate_left_15_reg_1678_pp0_iter10_reg;
wire   [11:0] addr_right_fu_728_p2;
reg   [11:0] addr_right_reg_1684;
wire   [11:0] addr_right_1_fu_736_p2;
reg   [11:0] addr_right_1_reg_1690;
wire   [11:0] addr_right_2_fu_744_p2;
reg   [11:0] addr_right_2_reg_1696;
wire   [11:0] addr_right_3_fu_752_p2;
reg   [11:0] addr_right_3_reg_1702;
wire   [11:0] addr_right_4_fu_760_p2;
reg   [11:0] addr_right_4_reg_1708;
wire   [11:0] addr_right_5_fu_768_p2;
reg   [11:0] addr_right_5_reg_1714;
wire   [11:0] addr_right_6_fu_776_p2;
reg   [11:0] addr_right_6_reg_1720;
wire   [11:0] addr_right_7_fu_784_p2;
reg   [11:0] addr_right_7_reg_1726;
wire   [11:0] addr_right_8_fu_792_p2;
reg   [11:0] addr_right_8_reg_1732;
wire   [11:0] addr_right_9_fu_800_p2;
reg   [11:0] addr_right_9_reg_1738;
wire   [11:0] addr_right_10_fu_808_p2;
reg   [11:0] addr_right_10_reg_1744;
wire   [11:0] addr_right_11_fu_816_p2;
reg   [11:0] addr_right_11_reg_1750;
wire   [11:0] addr_right_12_fu_824_p2;
reg   [11:0] addr_right_12_reg_1756;
wire   [11:0] addr_right_13_fu_832_p2;
reg   [11:0] addr_right_13_reg_1762;
wire   [11:0] addr_right_14_fu_840_p2;
reg   [11:0] addr_right_14_reg_1768;
wire   [11:0] addr_right_15_fu_848_p2;
reg   [11:0] addr_right_15_reg_1774;
wire    ap_block_pp0_stage0_01001;
wire    ap_block_pp0_stage0;
wire   [9:0] tmp2_fu_429_p2;
wire   [9:0] tmp2_1_fu_447_p2;
wire   [9:0] tmp2_2_fu_465_p2;
wire   [9:0] tmp2_3_fu_483_p2;
wire   [9:0] tmp2_4_fu_501_p2;
wire   [9:0] tmp2_5_fu_519_p2;
wire   [9:0] tmp2_6_fu_537_p2;
wire   [9:0] tmp2_7_fu_555_p2;
wire  signed [9:0] sext_ln26_fu_405_p1;
wire   [9:0] tmp2_8_fu_573_p2;
wire  signed [9:0] sext_ln26_1_fu_408_p1;
wire   [9:0] tmp2_9_fu_592_p2;
wire  signed [9:0] sext_ln26_2_fu_411_p1;
wire   [9:0] tmp2_10_fu_611_p2;
wire  signed [9:0] sext_ln26_3_fu_414_p1;
wire   [9:0] tmp2_11_fu_630_p2;
wire  signed [9:0] sext_ln26_4_fu_417_p1;
wire   [9:0] tmp2_12_fu_649_p2;
wire  signed [9:0] sext_ln26_5_fu_420_p1;
wire   [9:0] tmp2_13_fu_668_p2;
wire  signed [9:0] sext_ln26_6_fu_423_p1;
wire   [9:0] tmp2_14_fu_687_p2;
wire  signed [9:0] sext_ln26_7_fu_426_p1;
wire   [9:0] tmp2_15_fu_706_p2;
wire   [11:0] zext_ln54_fu_725_p1;
wire   [11:0] zext_ln54_1_fu_733_p1;
wire   [11:0] zext_ln54_2_fu_741_p1;
wire   [11:0] zext_ln54_3_fu_749_p1;
wire   [11:0] zext_ln54_4_fu_757_p1;
wire   [11:0] zext_ln54_5_fu_765_p1;
wire   [11:0] zext_ln54_6_fu_773_p1;
wire   [11:0] zext_ln54_7_fu_781_p1;
wire   [11:0] zext_ln54_8_fu_789_p1;
wire   [11:0] zext_ln54_9_fu_797_p1;
wire   [11:0] zext_ln54_10_fu_805_p1;
wire   [11:0] zext_ln54_11_fu_813_p1;
wire   [11:0] zext_ln54_12_fu_821_p1;
wire   [11:0] zext_ln54_13_fu_829_p1;
wire   [11:0] zext_ln54_14_fu_837_p1;
wire   [11:0] zext_ln54_15_fu_845_p1;
wire   [5:0] zext_ln57_fu_858_p1;
wire   [5:0] zext_ln57_1_fu_872_p1;
wire   [5:0] zext_ln57_2_fu_886_p1;
wire   [5:0] zext_ln57_3_fu_900_p1;
wire   [5:0] zext_ln57_4_fu_914_p1;
wire   [5:0] zext_ln57_5_fu_928_p1;
wire   [5:0] zext_ln57_6_fu_942_p1;
wire   [5:0] zext_ln57_7_fu_956_p1;
wire   [5:0] zext_ln57_8_fu_970_p1;
wire   [5:0] zext_ln57_9_fu_984_p1;
wire   [5:0] zext_ln57_10_fu_998_p1;
wire   [5:0] zext_ln57_11_fu_1012_p1;
wire   [5:0] zext_ln57_12_fu_1026_p1;
wire   [5:0] zext_ln57_13_fu_1040_p1;
wire   [5:0] zext_ln57_14_fu_1054_p1;
wire   [5:0] zext_ln57_15_fu_1068_p1;
wire   [11:0] addr_left_15_fu_1063_p2;
wire   [11:0] addr_left_14_fu_1049_p2;
wire   [11:0] addr_left_13_fu_1035_p2;
wire   [11:0] addr_left_12_fu_1021_p2;
wire   [11:0] addr_left_11_fu_1007_p2;
wire   [11:0] addr_left_10_fu_993_p2;
wire   [11:0] addr_left_9_fu_979_p2;
wire   [11:0] addr_left_8_fu_965_p2;
wire   [11:0] addr_left_7_fu_951_p2;
wire   [11:0] addr_left_6_fu_937_p2;
wire   [11:0] addr_left_5_fu_923_p2;
wire   [11:0] addr_left_4_fu_909_p2;
wire   [11:0] addr_left_3_fu_895_p2;
wire   [11:0] addr_left_2_fu_881_p2;
wire   [11:0] addr_left_1_fu_867_p2;
wire   [11:0] addr_left_fu_853_p2;
wire   [5:0] rate_right_15_fu_1071_p2;
wire   [5:0] rate_right_14_fu_1057_p2;
wire   [5:0] rate_right_13_fu_1043_p2;
wire   [5:0] rate_right_12_fu_1029_p2;
wire   [5:0] rate_right_11_fu_1015_p2;
wire   [5:0] rate_right_10_fu_1001_p2;
wire   [5:0] rate_right_9_fu_987_p2;
wire   [5:0] rate_right_8_fu_973_p2;
wire   [5:0] rate_right_7_fu_959_p2;
wire   [5:0] rate_right_6_fu_945_p2;
wire   [5:0] rate_right_5_fu_931_p2;
wire   [5:0] rate_right_4_fu_917_p2;
wire   [5:0] rate_right_3_fu_903_p2;
wire   [5:0] rate_right_2_fu_889_p2;
wire   [5:0] rate_right_1_fu_875_p2;
wire   [5:0] rate_right_fu_861_p2;
wire    ap_ce_reg;

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        addr_right_10_reg_1744 <= addr_right_10_fu_808_p2;
        addr_right_11_reg_1750 <= addr_right_11_fu_816_p2;
        addr_right_12_reg_1756 <= addr_right_12_fu_824_p2;
        addr_right_13_reg_1762 <= addr_right_13_fu_832_p2;
        addr_right_14_reg_1768 <= addr_right_14_fu_840_p2;
        addr_right_15_reg_1774 <= addr_right_15_fu_848_p2;
        addr_right_1_reg_1690 <= addr_right_1_fu_736_p2;
        addr_right_2_reg_1696 <= addr_right_2_fu_744_p2;
        addr_right_3_reg_1702 <= addr_right_3_fu_752_p2;
        addr_right_4_reg_1708 <= addr_right_4_fu_760_p2;
        addr_right_5_reg_1714 <= addr_right_5_fu_768_p2;
        addr_right_6_reg_1720 <= addr_right_6_fu_776_p2;
        addr_right_7_reg_1726 <= addr_right_7_fu_784_p2;
        addr_right_8_reg_1732 <= addr_right_8_fu_792_p2;
        addr_right_9_reg_1738 <= addr_right_9_fu_800_p2;
        addr_right_reg_1684 <= addr_right_fu_728_p2;
        addr_signed_10_reg_1283 <= {{addrs_signed[19:11]}};
        addr_signed_10_reg_1283_pp0_iter1_reg <= addr_signed_10_reg_1283;
        addr_signed_10_reg_1283_pp0_iter2_reg <= addr_signed_10_reg_1283_pp0_iter1_reg;
        addr_signed_10_reg_1283_pp0_iter3_reg <= addr_signed_10_reg_1283_pp0_iter2_reg;
        addr_signed_10_reg_1283_pp0_iter4_reg <= addr_signed_10_reg_1283_pp0_iter3_reg;
        addr_signed_10_reg_1283_pp0_iter5_reg <= addr_signed_10_reg_1283_pp0_iter4_reg;
        addr_signed_10_reg_1283_pp0_iter6_reg <= addr_signed_10_reg_1283_pp0_iter5_reg;
        addr_signed_10_reg_1283_pp0_iter7_reg <= addr_signed_10_reg_1283_pp0_iter6_reg;
        addr_signed_10_reg_1283_pp0_iter8_reg <= addr_signed_10_reg_1283_pp0_iter7_reg;
        addr_signed_11_reg_1290 <= {{addrs_signed[9:1]}};
        addr_signed_11_reg_1290_pp0_iter1_reg <= addr_signed_11_reg_1290;
        addr_signed_11_reg_1290_pp0_iter2_reg <= addr_signed_11_reg_1290_pp0_iter1_reg;
        addr_signed_11_reg_1290_pp0_iter3_reg <= addr_signed_11_reg_1290_pp0_iter2_reg;
        addr_signed_11_reg_1290_pp0_iter4_reg <= addr_signed_11_reg_1290_pp0_iter3_reg;
        addr_signed_11_reg_1290_pp0_iter5_reg <= addr_signed_11_reg_1290_pp0_iter4_reg;
        addr_signed_11_reg_1290_pp0_iter6_reg <= addr_signed_11_reg_1290_pp0_iter5_reg;
        addr_signed_11_reg_1290_pp0_iter7_reg <= addr_signed_11_reg_1290_pp0_iter6_reg;
        addr_signed_11_reg_1290_pp0_iter8_reg <= addr_signed_11_reg_1290_pp0_iter7_reg;
        addr_signed_12_reg_1297 <= {{addr_signed_4_fu_162_p2[9:1]}};
        addr_signed_12_reg_1297_pp0_iter1_reg <= addr_signed_12_reg_1297;
        addr_signed_12_reg_1297_pp0_iter2_reg <= addr_signed_12_reg_1297_pp0_iter1_reg;
        addr_signed_12_reg_1297_pp0_iter3_reg <= addr_signed_12_reg_1297_pp0_iter2_reg;
        addr_signed_12_reg_1297_pp0_iter4_reg <= addr_signed_12_reg_1297_pp0_iter3_reg;
        addr_signed_12_reg_1297_pp0_iter5_reg <= addr_signed_12_reg_1297_pp0_iter4_reg;
        addr_signed_12_reg_1297_pp0_iter6_reg <= addr_signed_12_reg_1297_pp0_iter5_reg;
        addr_signed_12_reg_1297_pp0_iter7_reg <= addr_signed_12_reg_1297_pp0_iter6_reg;
        addr_signed_12_reg_1297_pp0_iter8_reg <= addr_signed_12_reg_1297_pp0_iter7_reg;
        addr_signed_13_reg_1304 <= {{addr_signed_5_fu_168_p2[9:1]}};
        addr_signed_13_reg_1304_pp0_iter1_reg <= addr_signed_13_reg_1304;
        addr_signed_13_reg_1304_pp0_iter2_reg <= addr_signed_13_reg_1304_pp0_iter1_reg;
        addr_signed_13_reg_1304_pp0_iter3_reg <= addr_signed_13_reg_1304_pp0_iter2_reg;
        addr_signed_13_reg_1304_pp0_iter4_reg <= addr_signed_13_reg_1304_pp0_iter3_reg;
        addr_signed_13_reg_1304_pp0_iter5_reg <= addr_signed_13_reg_1304_pp0_iter4_reg;
        addr_signed_13_reg_1304_pp0_iter6_reg <= addr_signed_13_reg_1304_pp0_iter5_reg;
        addr_signed_13_reg_1304_pp0_iter7_reg <= addr_signed_13_reg_1304_pp0_iter6_reg;
        addr_signed_13_reg_1304_pp0_iter8_reg <= addr_signed_13_reg_1304_pp0_iter7_reg;
        addr_signed_14_reg_1311 <= {{addr_signed_6_fu_174_p2[9:1]}};
        addr_signed_14_reg_1311_pp0_iter1_reg <= addr_signed_14_reg_1311;
        addr_signed_14_reg_1311_pp0_iter2_reg <= addr_signed_14_reg_1311_pp0_iter1_reg;
        addr_signed_14_reg_1311_pp0_iter3_reg <= addr_signed_14_reg_1311_pp0_iter2_reg;
        addr_signed_14_reg_1311_pp0_iter4_reg <= addr_signed_14_reg_1311_pp0_iter3_reg;
        addr_signed_14_reg_1311_pp0_iter5_reg <= addr_signed_14_reg_1311_pp0_iter4_reg;
        addr_signed_14_reg_1311_pp0_iter6_reg <= addr_signed_14_reg_1311_pp0_iter5_reg;
        addr_signed_14_reg_1311_pp0_iter7_reg <= addr_signed_14_reg_1311_pp0_iter6_reg;
        addr_signed_14_reg_1311_pp0_iter8_reg <= addr_signed_14_reg_1311_pp0_iter7_reg;
        addr_signed_15_reg_1318 <= {{addr_signed_7_fu_180_p2[9:1]}};
        addr_signed_15_reg_1318_pp0_iter1_reg <= addr_signed_15_reg_1318;
        addr_signed_15_reg_1318_pp0_iter2_reg <= addr_signed_15_reg_1318_pp0_iter1_reg;
        addr_signed_15_reg_1318_pp0_iter3_reg <= addr_signed_15_reg_1318_pp0_iter2_reg;
        addr_signed_15_reg_1318_pp0_iter4_reg <= addr_signed_15_reg_1318_pp0_iter3_reg;
        addr_signed_15_reg_1318_pp0_iter5_reg <= addr_signed_15_reg_1318_pp0_iter4_reg;
        addr_signed_15_reg_1318_pp0_iter6_reg <= addr_signed_15_reg_1318_pp0_iter5_reg;
        addr_signed_15_reg_1318_pp0_iter7_reg <= addr_signed_15_reg_1318_pp0_iter6_reg;
        addr_signed_15_reg_1318_pp0_iter8_reg <= addr_signed_15_reg_1318_pp0_iter7_reg;
        addr_signed_1_reg_1220 <= {{addrs_signed[29:20]}};
        addr_signed_1_reg_1220_pp0_iter1_reg <= addr_signed_1_reg_1220;
        addr_signed_1_reg_1220_pp0_iter2_reg <= addr_signed_1_reg_1220_pp0_iter1_reg;
        addr_signed_1_reg_1220_pp0_iter3_reg <= addr_signed_1_reg_1220_pp0_iter2_reg;
        addr_signed_1_reg_1220_pp0_iter4_reg <= addr_signed_1_reg_1220_pp0_iter3_reg;
        addr_signed_1_reg_1220_pp0_iter5_reg <= addr_signed_1_reg_1220_pp0_iter4_reg;
        addr_signed_1_reg_1220_pp0_iter6_reg <= addr_signed_1_reg_1220_pp0_iter5_reg;
        addr_signed_1_reg_1220_pp0_iter7_reg <= addr_signed_1_reg_1220_pp0_iter6_reg;
        addr_signed_1_reg_1220_pp0_iter8_reg <= addr_signed_1_reg_1220_pp0_iter7_reg;
        addr_signed_2_reg_1227 <= {{addrs_signed[19:10]}};
        addr_signed_2_reg_1227_pp0_iter1_reg <= addr_signed_2_reg_1227;
        addr_signed_2_reg_1227_pp0_iter2_reg <= addr_signed_2_reg_1227_pp0_iter1_reg;
        addr_signed_2_reg_1227_pp0_iter3_reg <= addr_signed_2_reg_1227_pp0_iter2_reg;
        addr_signed_2_reg_1227_pp0_iter4_reg <= addr_signed_2_reg_1227_pp0_iter3_reg;
        addr_signed_2_reg_1227_pp0_iter5_reg <= addr_signed_2_reg_1227_pp0_iter4_reg;
        addr_signed_2_reg_1227_pp0_iter6_reg <= addr_signed_2_reg_1227_pp0_iter5_reg;
        addr_signed_2_reg_1227_pp0_iter7_reg <= addr_signed_2_reg_1227_pp0_iter6_reg;
        addr_signed_2_reg_1227_pp0_iter8_reg <= addr_signed_2_reg_1227_pp0_iter7_reg;
        addr_signed_3_reg_1234 <= addr_signed_3_fu_158_p1;
        addr_signed_3_reg_1234_pp0_iter1_reg <= addr_signed_3_reg_1234;
        addr_signed_3_reg_1234_pp0_iter2_reg <= addr_signed_3_reg_1234_pp0_iter1_reg;
        addr_signed_3_reg_1234_pp0_iter3_reg <= addr_signed_3_reg_1234_pp0_iter2_reg;
        addr_signed_3_reg_1234_pp0_iter4_reg <= addr_signed_3_reg_1234_pp0_iter3_reg;
        addr_signed_3_reg_1234_pp0_iter5_reg <= addr_signed_3_reg_1234_pp0_iter4_reg;
        addr_signed_3_reg_1234_pp0_iter6_reg <= addr_signed_3_reg_1234_pp0_iter5_reg;
        addr_signed_3_reg_1234_pp0_iter7_reg <= addr_signed_3_reg_1234_pp0_iter6_reg;
        addr_signed_3_reg_1234_pp0_iter8_reg <= addr_signed_3_reg_1234_pp0_iter7_reg;
        addr_signed_4_reg_1241 <= addr_signed_4_fu_162_p2;
        addr_signed_4_reg_1241_pp0_iter1_reg <= addr_signed_4_reg_1241;
        addr_signed_4_reg_1241_pp0_iter2_reg <= addr_signed_4_reg_1241_pp0_iter1_reg;
        addr_signed_4_reg_1241_pp0_iter3_reg <= addr_signed_4_reg_1241_pp0_iter2_reg;
        addr_signed_4_reg_1241_pp0_iter4_reg <= addr_signed_4_reg_1241_pp0_iter3_reg;
        addr_signed_4_reg_1241_pp0_iter5_reg <= addr_signed_4_reg_1241_pp0_iter4_reg;
        addr_signed_4_reg_1241_pp0_iter6_reg <= addr_signed_4_reg_1241_pp0_iter5_reg;
        addr_signed_4_reg_1241_pp0_iter7_reg <= addr_signed_4_reg_1241_pp0_iter6_reg;
        addr_signed_4_reg_1241_pp0_iter8_reg <= addr_signed_4_reg_1241_pp0_iter7_reg;
        addr_signed_5_reg_1248 <= addr_signed_5_fu_168_p2;
        addr_signed_5_reg_1248_pp0_iter1_reg <= addr_signed_5_reg_1248;
        addr_signed_5_reg_1248_pp0_iter2_reg <= addr_signed_5_reg_1248_pp0_iter1_reg;
        addr_signed_5_reg_1248_pp0_iter3_reg <= addr_signed_5_reg_1248_pp0_iter2_reg;
        addr_signed_5_reg_1248_pp0_iter4_reg <= addr_signed_5_reg_1248_pp0_iter3_reg;
        addr_signed_5_reg_1248_pp0_iter5_reg <= addr_signed_5_reg_1248_pp0_iter4_reg;
        addr_signed_5_reg_1248_pp0_iter6_reg <= addr_signed_5_reg_1248_pp0_iter5_reg;
        addr_signed_5_reg_1248_pp0_iter7_reg <= addr_signed_5_reg_1248_pp0_iter6_reg;
        addr_signed_5_reg_1248_pp0_iter8_reg <= addr_signed_5_reg_1248_pp0_iter7_reg;
        addr_signed_6_reg_1255 <= addr_signed_6_fu_174_p2;
        addr_signed_6_reg_1255_pp0_iter1_reg <= addr_signed_6_reg_1255;
        addr_signed_6_reg_1255_pp0_iter2_reg <= addr_signed_6_reg_1255_pp0_iter1_reg;
        addr_signed_6_reg_1255_pp0_iter3_reg <= addr_signed_6_reg_1255_pp0_iter2_reg;
        addr_signed_6_reg_1255_pp0_iter4_reg <= addr_signed_6_reg_1255_pp0_iter3_reg;
        addr_signed_6_reg_1255_pp0_iter5_reg <= addr_signed_6_reg_1255_pp0_iter4_reg;
        addr_signed_6_reg_1255_pp0_iter6_reg <= addr_signed_6_reg_1255_pp0_iter5_reg;
        addr_signed_6_reg_1255_pp0_iter7_reg <= addr_signed_6_reg_1255_pp0_iter6_reg;
        addr_signed_6_reg_1255_pp0_iter8_reg <= addr_signed_6_reg_1255_pp0_iter7_reg;
        addr_signed_7_reg_1262 <= addr_signed_7_fu_180_p2;
        addr_signed_7_reg_1262_pp0_iter1_reg <= addr_signed_7_reg_1262;
        addr_signed_7_reg_1262_pp0_iter2_reg <= addr_signed_7_reg_1262_pp0_iter1_reg;
        addr_signed_7_reg_1262_pp0_iter3_reg <= addr_signed_7_reg_1262_pp0_iter2_reg;
        addr_signed_7_reg_1262_pp0_iter4_reg <= addr_signed_7_reg_1262_pp0_iter3_reg;
        addr_signed_7_reg_1262_pp0_iter5_reg <= addr_signed_7_reg_1262_pp0_iter4_reg;
        addr_signed_7_reg_1262_pp0_iter6_reg <= addr_signed_7_reg_1262_pp0_iter5_reg;
        addr_signed_7_reg_1262_pp0_iter7_reg <= addr_signed_7_reg_1262_pp0_iter6_reg;
        addr_signed_7_reg_1262_pp0_iter8_reg <= addr_signed_7_reg_1262_pp0_iter7_reg;
        addr_signed_8_reg_1269 <= {{addrs_signed[39:31]}};
        addr_signed_8_reg_1269_pp0_iter1_reg <= addr_signed_8_reg_1269;
        addr_signed_8_reg_1269_pp0_iter2_reg <= addr_signed_8_reg_1269_pp0_iter1_reg;
        addr_signed_8_reg_1269_pp0_iter3_reg <= addr_signed_8_reg_1269_pp0_iter2_reg;
        addr_signed_8_reg_1269_pp0_iter4_reg <= addr_signed_8_reg_1269_pp0_iter3_reg;
        addr_signed_8_reg_1269_pp0_iter5_reg <= addr_signed_8_reg_1269_pp0_iter4_reg;
        addr_signed_8_reg_1269_pp0_iter6_reg <= addr_signed_8_reg_1269_pp0_iter5_reg;
        addr_signed_8_reg_1269_pp0_iter7_reg <= addr_signed_8_reg_1269_pp0_iter6_reg;
        addr_signed_8_reg_1269_pp0_iter8_reg <= addr_signed_8_reg_1269_pp0_iter7_reg;
        addr_signed_9_reg_1276 <= {{addrs_signed[29:21]}};
        addr_signed_9_reg_1276_pp0_iter1_reg <= addr_signed_9_reg_1276;
        addr_signed_9_reg_1276_pp0_iter2_reg <= addr_signed_9_reg_1276_pp0_iter1_reg;
        addr_signed_9_reg_1276_pp0_iter3_reg <= addr_signed_9_reg_1276_pp0_iter2_reg;
        addr_signed_9_reg_1276_pp0_iter4_reg <= addr_signed_9_reg_1276_pp0_iter3_reg;
        addr_signed_9_reg_1276_pp0_iter5_reg <= addr_signed_9_reg_1276_pp0_iter4_reg;
        addr_signed_9_reg_1276_pp0_iter6_reg <= addr_signed_9_reg_1276_pp0_iter5_reg;
        addr_signed_9_reg_1276_pp0_iter7_reg <= addr_signed_9_reg_1276_pp0_iter6_reg;
        addr_signed_9_reg_1276_pp0_iter8_reg <= addr_signed_9_reg_1276_pp0_iter7_reg;
        addr_signed_reg_1213 <= {{addrs_signed[39:30]}};
        addr_signed_reg_1213_pp0_iter1_reg <= addr_signed_reg_1213;
        addr_signed_reg_1213_pp0_iter2_reg <= addr_signed_reg_1213_pp0_iter1_reg;
        addr_signed_reg_1213_pp0_iter3_reg <= addr_signed_reg_1213_pp0_iter2_reg;
        addr_signed_reg_1213_pp0_iter4_reg <= addr_signed_reg_1213_pp0_iter3_reg;
        addr_signed_reg_1213_pp0_iter5_reg <= addr_signed_reg_1213_pp0_iter4_reg;
        addr_signed_reg_1213_pp0_iter6_reg <= addr_signed_reg_1213_pp0_iter5_reg;
        addr_signed_reg_1213_pp0_iter7_reg <= addr_signed_reg_1213_pp0_iter6_reg;
        addr_signed_reg_1213_pp0_iter8_reg <= addr_signed_reg_1213_pp0_iter7_reg;
        icmp_ln247_10_reg_1423 <= icmp_ln247_10_fu_346_p2;
        icmp_ln247_11_reg_1428 <= icmp_ln247_11_fu_350_p2;
        icmp_ln247_12_reg_1457 <= icmp_ln247_12_fu_374_p2;
        icmp_ln247_13_reg_1462 <= icmp_ln247_13_fu_378_p2;
        icmp_ln247_14_reg_1483 <= icmp_ln247_14_fu_395_p2;
        icmp_ln247_1_reg_1330 <= icmp_ln247_1_fu_270_p2;
        icmp_ln247_2_reg_1335 <= icmp_ln247_2_fu_274_p2;
        icmp_ln247_3_reg_1340 <= icmp_ln247_3_fu_278_p2;
        icmp_ln247_4_reg_1345 <= icmp_ln247_4_fu_282_p2;
        icmp_ln247_5_reg_1350 <= icmp_ln247_5_fu_286_p2;
        icmp_ln247_6_reg_1355 <= icmp_ln247_6_fu_290_p2;
        icmp_ln247_7_reg_1360 <= icmp_ln247_7_fu_294_p2;
        icmp_ln247_8_reg_1413 <= icmp_ln247_8_fu_338_p2;
        icmp_ln247_9_reg_1418 <= icmp_ln247_9_fu_342_p2;
        icmp_ln247_reg_1325 <= icmp_ln247_fu_266_p2;
        min01_reg_1365 <= min01_fu_298_p3;
        min01_reg_1365_pp0_iter3_reg <= min01_reg_1365;
        min03_reg_1433 <= min03_fu_354_p3;
        min03_reg_1433_pp0_iter5_reg <= min03_reg_1433;
        min07_reg_1467 <= min07_fu_382_p3;
        min07_reg_1467_pp0_iter7_reg <= min07_reg_1467;
        min23_reg_1371 <= min23_fu_303_p3;
        min23_reg_1371_pp0_iter3_reg <= min23_reg_1371;
        min45_reg_1377 <= min45_fu_308_p3;
        min45_reg_1377_pp0_iter3_reg <= min45_reg_1377;
        min47_reg_1439 <= min47_fu_359_p3;
        min47_reg_1439_pp0_iter5_reg <= min47_reg_1439;
        min67_reg_1383 <= min67_fu_313_p3;
        min67_reg_1383_pp0_iter3_reg <= min67_reg_1383;
        min8F_reg_1473 <= min8F_fu_387_p3;
        min_value_reg_1488 <= min_value_fu_400_p3;
        now_read_reg_1193 <= now;
        now_read_reg_1193_pp0_iter1_reg <= now_read_reg_1193;
        now_read_reg_1193_pp0_iter2_reg <= now_read_reg_1193_pp0_iter1_reg;
        now_read_reg_1193_pp0_iter3_reg <= now_read_reg_1193_pp0_iter2_reg;
        now_read_reg_1193_pp0_iter4_reg <= now_read_reg_1193_pp0_iter3_reg;
        now_read_reg_1193_pp0_iter5_reg <= now_read_reg_1193_pp0_iter4_reg;
        now_read_reg_1193_pp0_iter6_reg <= now_read_reg_1193_pp0_iter5_reg;
        now_read_reg_1193_pp0_iter7_reg <= now_read_reg_1193_pp0_iter6_reg;
        now_read_reg_1193_pp0_iter8_reg <= now_read_reg_1193_pp0_iter7_reg;
        now_read_reg_1193_pp0_iter9_reg <= now_read_reg_1193_pp0_iter8_reg;
        rate_left_10_reg_1623 <= rate_left_10_fu_626_p1;
        rate_left_10_reg_1623_pp0_iter10_reg <= rate_left_10_reg_1623;
        rate_left_11_reg_1634 <= rate_left_11_fu_645_p1;
        rate_left_11_reg_1634_pp0_iter10_reg <= rate_left_11_reg_1634;
        rate_left_12_reg_1645 <= rate_left_12_fu_664_p1;
        rate_left_12_reg_1645_pp0_iter10_reg <= rate_left_12_reg_1645;
        rate_left_13_reg_1656 <= rate_left_13_fu_683_p1;
        rate_left_13_reg_1656_pp0_iter10_reg <= rate_left_13_reg_1656;
        rate_left_14_reg_1667 <= rate_left_14_fu_702_p1;
        rate_left_14_reg_1667_pp0_iter10_reg <= rate_left_14_reg_1667;
        rate_left_15_reg_1678 <= rate_left_15_fu_721_p1;
        rate_left_15_reg_1678_pp0_iter10_reg <= rate_left_15_reg_1678;
        rate_left_1_reg_1524 <= rate_left_1_fu_461_p1;
        rate_left_1_reg_1524_pp0_iter10_reg <= rate_left_1_reg_1524;
        rate_left_2_reg_1535 <= rate_left_2_fu_479_p1;
        rate_left_2_reg_1535_pp0_iter10_reg <= rate_left_2_reg_1535;
        rate_left_3_reg_1546 <= rate_left_3_fu_497_p1;
        rate_left_3_reg_1546_pp0_iter10_reg <= rate_left_3_reg_1546;
        rate_left_4_reg_1557 <= rate_left_4_fu_515_p1;
        rate_left_4_reg_1557_pp0_iter10_reg <= rate_left_4_reg_1557;
        rate_left_5_reg_1568 <= rate_left_5_fu_533_p1;
        rate_left_5_reg_1568_pp0_iter10_reg <= rate_left_5_reg_1568;
        rate_left_6_reg_1579 <= rate_left_6_fu_551_p1;
        rate_left_6_reg_1579_pp0_iter10_reg <= rate_left_6_reg_1579;
        rate_left_7_reg_1590 <= rate_left_7_fu_569_p1;
        rate_left_7_reg_1590_pp0_iter10_reg <= rate_left_7_reg_1590;
        rate_left_8_reg_1601 <= rate_left_8_fu_588_p1;
        rate_left_8_reg_1601_pp0_iter10_reg <= rate_left_8_reg_1601;
        rate_left_9_reg_1612 <= rate_left_9_fu_607_p1;
        rate_left_9_reg_1612_pp0_iter10_reg <= rate_left_9_reg_1612;
        rate_left_reg_1513 <= rate_left_fu_443_p1;
        rate_left_reg_1513_pp0_iter10_reg <= rate_left_reg_1513;
        select_ln247_1_reg_1395 <= select_ln247_1_fu_323_p3;
        select_ln247_1_reg_1395_pp0_iter3_reg <= select_ln247_1_reg_1395;
        select_ln247_2_reg_1401 <= select_ln247_2_fu_328_p3;
        select_ln247_2_reg_1401_pp0_iter3_reg <= select_ln247_2_reg_1401;
        select_ln247_3_reg_1407 <= select_ln247_3_fu_333_p3;
        select_ln247_3_reg_1407_pp0_iter3_reg <= select_ln247_3_reg_1407;
        select_ln247_6_reg_1445 <= select_ln247_6_fu_364_p3;
        select_ln247_6_reg_1445_pp0_iter5_reg <= select_ln247_6_reg_1445;
        select_ln247_7_reg_1451 <= select_ln247_7_fu_369_p3;
        select_ln247_7_reg_1451_pp0_iter5_reg <= select_ln247_7_reg_1451;
        select_ln247_reg_1389 <= select_ln247_fu_318_p3;
        select_ln247_reg_1389_pp0_iter3_reg <= select_ln247_reg_1389;
        sext_ln247_reg_1478 <= sext_ln247_fu_392_p1;
        tmp8_reg_1508 <= {{tmp2_fu_429_p2[9:5]}};
        tmp_10_reg_1629 <= {{tmp2_11_fu_630_p2[9:5]}};
        tmp_11_reg_1640 <= {{tmp2_12_fu_649_p2[9:5]}};
        tmp_12_reg_1651 <= {{tmp2_13_fu_668_p2[9:5]}};
        tmp_13_reg_1662 <= {{tmp2_14_fu_687_p2[9:5]}};
        tmp_14_reg_1673 <= {{tmp2_15_fu_706_p2[9:5]}};
        tmp_1_reg_1530 <= {{tmp2_2_fu_465_p2[9:5]}};
        tmp_2_reg_1541 <= {{tmp2_3_fu_483_p2[9:5]}};
        tmp_3_reg_1552 <= {{tmp2_4_fu_501_p2[9:5]}};
        tmp_4_reg_1563 <= {{tmp2_5_fu_519_p2[9:5]}};
        tmp_5_reg_1574 <= {{tmp2_6_fu_537_p2[9:5]}};
        tmp_6_reg_1585 <= {{tmp2_7_fu_555_p2[9:5]}};
        tmp_7_reg_1596 <= {{tmp2_8_fu_573_p2[9:5]}};
        tmp_8_reg_1607 <= {{tmp2_9_fu_592_p2[9:5]}};
        tmp_9_reg_1618 <= {{tmp2_10_fu_611_p2[9:5]}};
        tmp_s_reg_1519 <= {{tmp2_1_fu_447_p2[9:5]}};
    end
end

assign addr_left_10_fu_993_p2 = ($signed(addr_right_10_reg_1744) + $signed(12'd4095));

assign addr_left_11_fu_1007_p2 = ($signed(addr_right_11_reg_1750) + $signed(12'd4095));

assign addr_left_12_fu_1021_p2 = ($signed(addr_right_12_reg_1756) + $signed(12'd4095));

assign addr_left_13_fu_1035_p2 = ($signed(addr_right_13_reg_1762) + $signed(12'd4095));

assign addr_left_14_fu_1049_p2 = ($signed(addr_right_14_reg_1768) + $signed(12'd4095));

assign addr_left_15_fu_1063_p2 = ($signed(addr_right_15_reg_1774) + $signed(12'd4095));

assign addr_left_1_fu_867_p2 = ($signed(addr_right_1_reg_1690) + $signed(12'd4095));

assign addr_left_2_fu_881_p2 = ($signed(addr_right_2_reg_1696) + $signed(12'd4095));

assign addr_left_3_fu_895_p2 = ($signed(addr_right_3_reg_1702) + $signed(12'd4095));

assign addr_left_4_fu_909_p2 = ($signed(addr_right_4_reg_1708) + $signed(12'd4095));

assign addr_left_5_fu_923_p2 = ($signed(addr_right_5_reg_1714) + $signed(12'd4095));

assign addr_left_6_fu_937_p2 = ($signed(addr_right_6_reg_1720) + $signed(12'd4095));

assign addr_left_7_fu_951_p2 = ($signed(addr_right_7_reg_1726) + $signed(12'd4095));

assign addr_left_8_fu_965_p2 = ($signed(addr_right_8_reg_1732) + $signed(12'd4095));

assign addr_left_9_fu_979_p2 = ($signed(addr_right_9_reg_1738) + $signed(12'd4095));

assign addr_left_fu_853_p2 = ($signed(addr_right_reg_1684) + $signed(12'd4095));

assign addr_right_10_fu_808_p2 = (now_read_reg_1193_pp0_iter9_reg - zext_ln54_10_fu_805_p1);

assign addr_right_11_fu_816_p2 = (now_read_reg_1193_pp0_iter9_reg - zext_ln54_11_fu_813_p1);

assign addr_right_12_fu_824_p2 = (now_read_reg_1193_pp0_iter9_reg - zext_ln54_12_fu_821_p1);

assign addr_right_13_fu_832_p2 = (now_read_reg_1193_pp0_iter9_reg - zext_ln54_13_fu_829_p1);

assign addr_right_14_fu_840_p2 = (now_read_reg_1193_pp0_iter9_reg - zext_ln54_14_fu_837_p1);

assign addr_right_15_fu_848_p2 = (now_read_reg_1193_pp0_iter9_reg - zext_ln54_15_fu_845_p1);

assign addr_right_1_fu_736_p2 = (now_read_reg_1193_pp0_iter9_reg - zext_ln54_1_fu_733_p1);

assign addr_right_2_fu_744_p2 = (now_read_reg_1193_pp0_iter9_reg - zext_ln54_2_fu_741_p1);

assign addr_right_3_fu_752_p2 = (now_read_reg_1193_pp0_iter9_reg - zext_ln54_3_fu_749_p1);

assign addr_right_4_fu_760_p2 = (now_read_reg_1193_pp0_iter9_reg - zext_ln54_4_fu_757_p1);

assign addr_right_5_fu_768_p2 = (now_read_reg_1193_pp0_iter9_reg - zext_ln54_5_fu_765_p1);

assign addr_right_6_fu_776_p2 = (now_read_reg_1193_pp0_iter9_reg - zext_ln54_6_fu_773_p1);

assign addr_right_7_fu_784_p2 = (now_read_reg_1193_pp0_iter9_reg - zext_ln54_7_fu_781_p1);

assign addr_right_8_fu_792_p2 = (now_read_reg_1193_pp0_iter9_reg - zext_ln54_8_fu_789_p1);

assign addr_right_9_fu_800_p2 = (now_read_reg_1193_pp0_iter9_reg - zext_ln54_9_fu_797_p1);

assign addr_right_fu_728_p2 = (now_read_reg_1193_pp0_iter9_reg - zext_ln54_fu_725_p1);

assign addr_signed_1_fu_138_p4 = {{addrs_signed[29:20]}};

assign addr_signed_2_fu_148_p4 = {{addrs_signed[19:10]}};

assign addr_signed_3_fu_158_p1 = addrs_signed[9:0];

assign addr_signed_4_fu_162_p2 = (10'd0 - addr_signed_fu_128_p4);

assign addr_signed_5_fu_168_p2 = (10'd0 - addr_signed_1_fu_138_p4);

assign addr_signed_6_fu_174_p2 = (10'd0 - addr_signed_2_fu_148_p4);

assign addr_signed_7_fu_180_p2 = (10'd0 - addr_signed_3_fu_158_p1);

assign addr_signed_fu_128_p4 = {{addrs_signed[39:30]}};

assign addrs_left = {{{{{{{{{{{{{{{{addr_left_15_fu_1063_p2}, {addr_left_14_fu_1049_p2}}, {addr_left_13_fu_1035_p2}}, {addr_left_12_fu_1021_p2}}, {addr_left_11_fu_1007_p2}}, {addr_left_10_fu_993_p2}}, {addr_left_9_fu_979_p2}}, {addr_left_8_fu_965_p2}}, {addr_left_7_fu_951_p2}}, {addr_left_6_fu_937_p2}}, {addr_left_5_fu_923_p2}}, {addr_left_4_fu_909_p2}}, {addr_left_3_fu_895_p2}}, {addr_left_2_fu_881_p2}}, {addr_left_1_fu_867_p2}}, {addr_left_fu_853_p2}};

assign addrs_right = {{{{{{{{{{{{{{{{addr_right_15_reg_1774}, {addr_right_14_reg_1768}}, {addr_right_13_reg_1762}}, {addr_right_12_reg_1756}}, {addr_right_11_reg_1750}}, {addr_right_10_reg_1744}}, {addr_right_9_reg_1738}}, {addr_right_8_reg_1732}}, {addr_right_7_reg_1726}}, {addr_right_6_reg_1720}}, {addr_right_5_reg_1714}}, {addr_right_4_reg_1708}}, {addr_right_3_reg_1702}}, {addr_right_2_reg_1696}}, {addr_right_1_reg_1690}}, {addr_right_reg_1684}};

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign icmp_ln247_10_fu_346_p2 = (($signed(select_ln247_reg_1389) < $signed(select_ln247_1_reg_1395)) ? 1'b1 : 1'b0);

assign icmp_ln247_11_fu_350_p2 = (($signed(select_ln247_2_reg_1401) < $signed(select_ln247_3_reg_1407)) ? 1'b1 : 1'b0);

assign icmp_ln247_12_fu_374_p2 = (($signed(min03_reg_1433) < $signed(min47_reg_1439)) ? 1'b1 : 1'b0);

assign icmp_ln247_13_fu_378_p2 = (($signed(select_ln247_6_reg_1445) < $signed(select_ln247_7_reg_1451)) ? 1'b1 : 1'b0);

assign icmp_ln247_14_fu_395_p2 = (($signed(min07_reg_1467) < $signed(sext_ln247_fu_392_p1)) ? 1'b1 : 1'b0);

assign icmp_ln247_1_fu_270_p2 = (($signed(addr_signed_2_reg_1227) < $signed(addr_signed_3_reg_1234)) ? 1'b1 : 1'b0);

assign icmp_ln247_2_fu_274_p2 = (($signed(addr_signed_4_reg_1241) < $signed(addr_signed_5_reg_1248)) ? 1'b1 : 1'b0);

assign icmp_ln247_3_fu_278_p2 = (($signed(addr_signed_6_reg_1255) < $signed(addr_signed_7_reg_1262)) ? 1'b1 : 1'b0);

assign icmp_ln247_4_fu_282_p2 = (($signed(addr_signed_8_reg_1269) < $signed(addr_signed_9_reg_1276)) ? 1'b1 : 1'b0);

assign icmp_ln247_5_fu_286_p2 = (($signed(addr_signed_10_reg_1283) < $signed(addr_signed_11_reg_1290)) ? 1'b1 : 1'b0);

assign icmp_ln247_6_fu_290_p2 = (($signed(addr_signed_12_reg_1297) < $signed(addr_signed_13_reg_1304)) ? 1'b1 : 1'b0);

assign icmp_ln247_7_fu_294_p2 = (($signed(addr_signed_14_reg_1311) < $signed(addr_signed_15_reg_1318)) ? 1'b1 : 1'b0);

assign icmp_ln247_8_fu_338_p2 = (($signed(min01_reg_1365) < $signed(min23_reg_1371)) ? 1'b1 : 1'b0);

assign icmp_ln247_9_fu_342_p2 = (($signed(min45_reg_1377) < $signed(min67_reg_1383)) ? 1'b1 : 1'b0);

assign icmp_ln247_fu_266_p2 = (($signed(addr_signed_reg_1213) < $signed(addr_signed_1_reg_1220)) ? 1'b1 : 1'b0);

assign min01_fu_298_p3 = ((icmp_ln247_reg_1325[0:0] == 1'b1) ? addr_signed_reg_1213_pp0_iter1_reg : addr_signed_1_reg_1220_pp0_iter1_reg);

assign min03_fu_354_p3 = ((icmp_ln247_8_reg_1413[0:0] == 1'b1) ? min01_reg_1365_pp0_iter3_reg : min23_reg_1371_pp0_iter3_reg);

assign min07_fu_382_p3 = ((icmp_ln247_12_reg_1457[0:0] == 1'b1) ? min03_reg_1433_pp0_iter5_reg : min47_reg_1439_pp0_iter5_reg);

assign min23_fu_303_p3 = ((icmp_ln247_1_reg_1330[0:0] == 1'b1) ? addr_signed_2_reg_1227_pp0_iter1_reg : addr_signed_3_reg_1234_pp0_iter1_reg);

assign min45_fu_308_p3 = ((icmp_ln247_2_reg_1335[0:0] == 1'b1) ? addr_signed_4_reg_1241_pp0_iter1_reg : addr_signed_5_reg_1248_pp0_iter1_reg);

assign min47_fu_359_p3 = ((icmp_ln247_9_reg_1418[0:0] == 1'b1) ? min45_reg_1377_pp0_iter3_reg : min67_reg_1383_pp0_iter3_reg);

assign min67_fu_313_p3 = ((icmp_ln247_3_reg_1340[0:0] == 1'b1) ? addr_signed_6_reg_1255_pp0_iter1_reg : addr_signed_7_reg_1262_pp0_iter1_reg);

assign min8F_fu_387_p3 = ((icmp_ln247_13_reg_1462[0:0] == 1'b1) ? select_ln247_6_reg_1445_pp0_iter5_reg : select_ln247_7_reg_1451_pp0_iter5_reg);

assign min_value_fu_400_p3 = ((icmp_ln247_14_reg_1483[0:0] == 1'b1) ? min07_reg_1467_pp0_iter7_reg : sext_ln247_reg_1478);

assign rate_left_10_fu_626_p1 = tmp2_10_fu_611_p2[4:0];

assign rate_left_11_fu_645_p1 = tmp2_11_fu_630_p2[4:0];

assign rate_left_12_fu_664_p1 = tmp2_12_fu_649_p2[4:0];

assign rate_left_13_fu_683_p1 = tmp2_13_fu_668_p2[4:0];

assign rate_left_14_fu_702_p1 = tmp2_14_fu_687_p2[4:0];

assign rate_left_15_fu_721_p1 = tmp2_15_fu_706_p2[4:0];

assign rate_left_1_fu_461_p1 = tmp2_1_fu_447_p2[4:0];

assign rate_left_2_fu_479_p1 = tmp2_2_fu_465_p2[4:0];

assign rate_left_3_fu_497_p1 = tmp2_3_fu_483_p2[4:0];

assign rate_left_4_fu_515_p1 = tmp2_4_fu_501_p2[4:0];

assign rate_left_5_fu_533_p1 = tmp2_5_fu_519_p2[4:0];

assign rate_left_6_fu_551_p1 = tmp2_6_fu_537_p2[4:0];

assign rate_left_7_fu_569_p1 = tmp2_7_fu_555_p2[4:0];

assign rate_left_8_fu_588_p1 = tmp2_8_fu_573_p2[4:0];

assign rate_left_9_fu_607_p1 = tmp2_9_fu_592_p2[4:0];

assign rate_left_fu_443_p1 = tmp2_fu_429_p2[4:0];

assign rate_right_10_fu_1001_p2 = ($signed(6'd32) - $signed(zext_ln57_10_fu_998_p1));

assign rate_right_11_fu_1015_p2 = ($signed(6'd32) - $signed(zext_ln57_11_fu_1012_p1));

assign rate_right_12_fu_1029_p2 = ($signed(6'd32) - $signed(zext_ln57_12_fu_1026_p1));

assign rate_right_13_fu_1043_p2 = ($signed(6'd32) - $signed(zext_ln57_13_fu_1040_p1));

assign rate_right_14_fu_1057_p2 = ($signed(6'd32) - $signed(zext_ln57_14_fu_1054_p1));

assign rate_right_15_fu_1071_p2 = ($signed(6'd32) - $signed(zext_ln57_15_fu_1068_p1));

assign rate_right_1_fu_875_p2 = ($signed(6'd32) - $signed(zext_ln57_1_fu_872_p1));

assign rate_right_2_fu_889_p2 = ($signed(6'd32) - $signed(zext_ln57_2_fu_886_p1));

assign rate_right_3_fu_903_p2 = ($signed(6'd32) - $signed(zext_ln57_3_fu_900_p1));

assign rate_right_4_fu_917_p2 = ($signed(6'd32) - $signed(zext_ln57_4_fu_914_p1));

assign rate_right_5_fu_931_p2 = ($signed(6'd32) - $signed(zext_ln57_5_fu_928_p1));

assign rate_right_6_fu_945_p2 = ($signed(6'd32) - $signed(zext_ln57_6_fu_942_p1));

assign rate_right_7_fu_959_p2 = ($signed(6'd32) - $signed(zext_ln57_7_fu_956_p1));

assign rate_right_8_fu_973_p2 = ($signed(6'd32) - $signed(zext_ln57_8_fu_970_p1));

assign rate_right_9_fu_987_p2 = ($signed(6'd32) - $signed(zext_ln57_9_fu_984_p1));

assign rate_right_fu_861_p2 = ($signed(6'd32) - $signed(zext_ln57_fu_858_p1));

assign rates_left = {{{{{{{{{{{{{{{{rate_left_15_reg_1678_pp0_iter10_reg}, {rate_left_14_reg_1667_pp0_iter10_reg}}, {rate_left_13_reg_1656_pp0_iter10_reg}}, {rate_left_12_reg_1645_pp0_iter10_reg}}, {rate_left_11_reg_1634_pp0_iter10_reg}}, {rate_left_10_reg_1623_pp0_iter10_reg}}, {rate_left_9_reg_1612_pp0_iter10_reg}}, {rate_left_8_reg_1601_pp0_iter10_reg}}, {rate_left_7_reg_1590_pp0_iter10_reg}}, {rate_left_6_reg_1579_pp0_iter10_reg}}, {rate_left_5_reg_1568_pp0_iter10_reg}}, {rate_left_4_reg_1557_pp0_iter10_reg}}, {rate_left_3_reg_1546_pp0_iter10_reg}}, {rate_left_2_reg_1535_pp0_iter10_reg}}, {rate_left_1_reg_1524_pp0_iter10_reg}}, {rate_left_reg_1513_pp0_iter10_reg}};

assign rates_right = {{{{{{{{{{{{{{{{rate_right_15_fu_1071_p2}, {rate_right_14_fu_1057_p2}}, {rate_right_13_fu_1043_p2}}, {rate_right_12_fu_1029_p2}}, {rate_right_11_fu_1015_p2}}, {rate_right_10_fu_1001_p2}}, {rate_right_9_fu_987_p2}}, {rate_right_8_fu_973_p2}}, {rate_right_7_fu_959_p2}}, {rate_right_6_fu_945_p2}}, {rate_right_5_fu_931_p2}}, {rate_right_4_fu_917_p2}}, {rate_right_3_fu_903_p2}}, {rate_right_2_fu_889_p2}}, {rate_right_1_fu_875_p2}}, {rate_right_fu_861_p2}};

assign select_ln247_1_fu_323_p3 = ((icmp_ln247_5_reg_1350[0:0] == 1'b1) ? addr_signed_10_reg_1283_pp0_iter1_reg : addr_signed_11_reg_1290_pp0_iter1_reg);

assign select_ln247_2_fu_328_p3 = ((icmp_ln247_6_reg_1355[0:0] == 1'b1) ? addr_signed_12_reg_1297_pp0_iter1_reg : addr_signed_13_reg_1304_pp0_iter1_reg);

assign select_ln247_3_fu_333_p3 = ((icmp_ln247_7_reg_1360[0:0] == 1'b1) ? addr_signed_14_reg_1311_pp0_iter1_reg : addr_signed_15_reg_1318_pp0_iter1_reg);

assign select_ln247_6_fu_364_p3 = ((icmp_ln247_10_reg_1423[0:0] == 1'b1) ? select_ln247_reg_1389_pp0_iter3_reg : select_ln247_1_reg_1395_pp0_iter3_reg);

assign select_ln247_7_fu_369_p3 = ((icmp_ln247_11_reg_1428[0:0] == 1'b1) ? select_ln247_2_reg_1401_pp0_iter3_reg : select_ln247_3_reg_1407_pp0_iter3_reg);

assign select_ln247_fu_318_p3 = ((icmp_ln247_4_reg_1345[0:0] == 1'b1) ? addr_signed_8_reg_1269_pp0_iter1_reg : addr_signed_9_reg_1276_pp0_iter1_reg);

assign sext_ln247_fu_392_p1 = $signed(min8F_reg_1473);

assign sext_ln26_1_fu_408_p1 = addr_signed_9_reg_1276_pp0_iter8_reg;

assign sext_ln26_2_fu_411_p1 = addr_signed_10_reg_1283_pp0_iter8_reg;

assign sext_ln26_3_fu_414_p1 = addr_signed_11_reg_1290_pp0_iter8_reg;

assign sext_ln26_4_fu_417_p1 = addr_signed_12_reg_1297_pp0_iter8_reg;

assign sext_ln26_5_fu_420_p1 = addr_signed_13_reg_1304_pp0_iter8_reg;

assign sext_ln26_6_fu_423_p1 = addr_signed_14_reg_1311_pp0_iter8_reg;

assign sext_ln26_7_fu_426_p1 = addr_signed_15_reg_1318_pp0_iter8_reg;

assign sext_ln26_fu_405_p1 = addr_signed_8_reg_1269_pp0_iter8_reg;

assign tmp2_10_fu_611_p2 = ($signed(sext_ln26_2_fu_411_p1) - $signed(min_value_reg_1488));

assign tmp2_11_fu_630_p2 = ($signed(sext_ln26_3_fu_414_p1) - $signed(min_value_reg_1488));

assign tmp2_12_fu_649_p2 = ($signed(sext_ln26_4_fu_417_p1) - $signed(min_value_reg_1488));

assign tmp2_13_fu_668_p2 = ($signed(sext_ln26_5_fu_420_p1) - $signed(min_value_reg_1488));

assign tmp2_14_fu_687_p2 = ($signed(sext_ln26_6_fu_423_p1) - $signed(min_value_reg_1488));

assign tmp2_15_fu_706_p2 = ($signed(sext_ln26_7_fu_426_p1) - $signed(min_value_reg_1488));

assign tmp2_1_fu_447_p2 = (addr_signed_1_reg_1220_pp0_iter8_reg - min_value_reg_1488);

assign tmp2_2_fu_465_p2 = (addr_signed_2_reg_1227_pp0_iter8_reg - min_value_reg_1488);

assign tmp2_3_fu_483_p2 = (addr_signed_3_reg_1234_pp0_iter8_reg - min_value_reg_1488);

assign tmp2_4_fu_501_p2 = (addr_signed_4_reg_1241_pp0_iter8_reg - min_value_reg_1488);

assign tmp2_5_fu_519_p2 = (addr_signed_5_reg_1248_pp0_iter8_reg - min_value_reg_1488);

assign tmp2_6_fu_537_p2 = (addr_signed_6_reg_1255_pp0_iter8_reg - min_value_reg_1488);

assign tmp2_7_fu_555_p2 = (addr_signed_7_reg_1262_pp0_iter8_reg - min_value_reg_1488);

assign tmp2_8_fu_573_p2 = ($signed(sext_ln26_fu_405_p1) - $signed(min_value_reg_1488));

assign tmp2_9_fu_592_p2 = ($signed(sext_ln26_1_fu_408_p1) - $signed(min_value_reg_1488));

assign tmp2_fu_429_p2 = (addr_signed_reg_1213_pp0_iter8_reg - min_value_reg_1488);

assign zext_ln54_10_fu_805_p1 = tmp_9_reg_1618;

assign zext_ln54_11_fu_813_p1 = tmp_10_reg_1629;

assign zext_ln54_12_fu_821_p1 = tmp_11_reg_1640;

assign zext_ln54_13_fu_829_p1 = tmp_12_reg_1651;

assign zext_ln54_14_fu_837_p1 = tmp_13_reg_1662;

assign zext_ln54_15_fu_845_p1 = tmp_14_reg_1673;

assign zext_ln54_1_fu_733_p1 = tmp_s_reg_1519;

assign zext_ln54_2_fu_741_p1 = tmp_1_reg_1530;

assign zext_ln54_3_fu_749_p1 = tmp_2_reg_1541;

assign zext_ln54_4_fu_757_p1 = tmp_3_reg_1552;

assign zext_ln54_5_fu_765_p1 = tmp_4_reg_1563;

assign zext_ln54_6_fu_773_p1 = tmp_5_reg_1574;

assign zext_ln54_7_fu_781_p1 = tmp_6_reg_1585;

assign zext_ln54_8_fu_789_p1 = tmp_7_reg_1596;

assign zext_ln54_9_fu_797_p1 = tmp_8_reg_1607;

assign zext_ln54_fu_725_p1 = tmp8_reg_1508;

assign zext_ln57_10_fu_998_p1 = rate_left_10_reg_1623_pp0_iter10_reg;

assign zext_ln57_11_fu_1012_p1 = rate_left_11_reg_1634_pp0_iter10_reg;

assign zext_ln57_12_fu_1026_p1 = rate_left_12_reg_1645_pp0_iter10_reg;

assign zext_ln57_13_fu_1040_p1 = rate_left_13_reg_1656_pp0_iter10_reg;

assign zext_ln57_14_fu_1054_p1 = rate_left_14_reg_1667_pp0_iter10_reg;

assign zext_ln57_15_fu_1068_p1 = rate_left_15_reg_1678_pp0_iter10_reg;

assign zext_ln57_1_fu_872_p1 = rate_left_1_reg_1524_pp0_iter10_reg;

assign zext_ln57_2_fu_886_p1 = rate_left_2_reg_1535_pp0_iter10_reg;

assign zext_ln57_3_fu_900_p1 = rate_left_3_reg_1546_pp0_iter10_reg;

assign zext_ln57_4_fu_914_p1 = rate_left_4_reg_1557_pp0_iter10_reg;

assign zext_ln57_5_fu_928_p1 = rate_left_5_reg_1568_pp0_iter10_reg;

assign zext_ln57_6_fu_942_p1 = rate_left_6_reg_1579_pp0_iter10_reg;

assign zext_ln57_7_fu_956_p1 = rate_left_7_reg_1590_pp0_iter10_reg;

assign zext_ln57_8_fu_970_p1 = rate_left_8_reg_1601_pp0_iter10_reg;

assign zext_ln57_9_fu_984_p1 = rate_left_9_reg_1612_pp0_iter10_reg;

assign zext_ln57_fu_858_p1 = rate_left_reg_1513_pp0_iter10_reg;

endmodule //delay
