// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="pixel_mapping_pixel_mapping,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-2,HLS_INPUT_CLOCK=13.468000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.180000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=26,HLS_VERSION=2024_1}" *)

module pixel_mapping (
        xpos,
        ypos,
        index,
        ap_rst
);


input  [10:0] xpos;
input  [10:0] ypos;
output  [13:0] index;
input   ap_rst;

wire   [10:0] mul_ln9_fu_67_p0;
wire   [12:0] mul_ln9_fu_67_p1;
wire   [22:0] mul_ln9_fu_67_p2;
wire   [6:0] tmp_fu_73_p4;
wire   [10:0] mul_ln9_1_fu_95_p0;
wire   [12:0] mul_ln9_1_fu_95_p1;
wire   [22:0] mul_ln9_1_fu_95_p2;
wire   [7:0] tmp_1_fu_101_p4;
wire   [13:0] shl_ln9_fu_83_p3;
wire   [13:0] zext_ln9_1_fu_111_p1;
wire   [22:0] mul_ln9_1_fu_95_p00;
wire   [22:0] mul_ln9_fu_67_p00;

pixel_mapping_mul_11ns_13ns_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 23 ))
mul_11ns_13ns_23_1_1_U1(
    .din0(mul_ln9_fu_67_p0),
    .din1(mul_ln9_fu_67_p1),
    .dout(mul_ln9_fu_67_p2)
);

pixel_mapping_mul_11ns_13ns_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 23 ))
mul_11ns_13ns_23_1_1_U2(
    .din0(mul_ln9_1_fu_95_p0),
    .din1(mul_ln9_1_fu_95_p1),
    .dout(mul_ln9_1_fu_95_p2)
);

assign mul_ln9_1_fu_95_p00 = xpos;

assign mul_ln9_fu_67_p00 = ypos;

assign shl_ln9_fu_83_p3 = {{tmp_fu_73_p4}, {7'd0}};

assign tmp_1_fu_101_p4 = {{mul_ln9_1_fu_95_p2[22:15]}};

assign tmp_fu_73_p4 = {{mul_ln9_fu_67_p2[21:15]}};

assign zext_ln9_1_fu_111_p1 = tmp_1_fu_101_p4;

assign index = (shl_ln9_fu_83_p3 + zext_ln9_1_fu_111_p1);

assign mul_ln9_1_fu_95_p0 = mul_ln9_1_fu_95_p00;

assign mul_ln9_1_fu_95_p1 = 23'd3277;

assign mul_ln9_fu_67_p0 = mul_ln9_fu_67_p00;

assign mul_ln9_fu_67_p1 = 23'd3277;

endmodule //pixel_mapping
