domain_path: C:\Users\16531\Desktop\mvdr_16\vitis\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2024.1\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
